In [ ]:
NER_LABELS = [
    "PERSON_NAME",
    "DATE_OF_BIRTH",
    "GENDER",
    "NATIONALITY",
    "PHONE",
    "EMAIL",
    "ADDRESS",
    "PINCODE",
    "SCHOOL_NAME",
    "COLLEGE_NAME",
    "DEGREE",
    "BRANCH",
    "BOARD",
    "YEAR_OF_PASSING",
    "PERCENTAGE",
    "CGPA",
    "ROLL_NUMBER",
    "COMPANY_NAME",
    "JOB_TITLE",
    "WORK_LOCATION",
    "WORK_DURATION",
    "SKILL",
    "CERTIFICATION",
    "PROJECT",
    "ID_NUMBER"
]

print("Number of NER labels:", len(NER_LABELS))
print(NER_LABELS)

Number of NER labels: 25
['PERSON_NAME', 'DATE_OF_BIRTH', 'GENDER', 'NATIONALITY', 'PHONE', 'EMAIL', 'ADDRESS', 'PINCODE', 'SCHOOL_NAME', 'COLLEGE_NAME', 'DEGREE', 'BRANCH', 'BOARD', 'YEAR_OF_PASSING', 'PERCENTAGE', 'CGPA', 'ROLL_NUMBER', 'COMPANY_NAME', 'JOB_TITLE', 'WORK_LOCATION', 'WORK_DURATION', 'SKILL', 'CERTIFICATION', 'PROJECT', 'ID_NUMBER']

In [ ]:
examples = [
    {
        "text": "My name is Arjun Kumar and I was born on 18 March 2003.",
        "entities": [
            ("Arjun Kumar", "PERSON_NAME"),
            ("18 March 2003", "DATE_OF_BIRTH")
        ]
    },
    {
        "text": "I studied at ABC High School under CBSE and passed in 2021 with 92.4%.",
        "entities": [
            ("ABC High School", "SCHOOL_NAME"),
            ("CBSE", "BOARD"),
            ("2021", "YEAR_OF_PASSING"),
            ("92.4%", "PERCENTAGE")
        ]
    },
    {
        "text": "I completed my B.Tech in Computer Science and Engineering from ABC Institute of Technology.",
        "entities": [
            ("B.Tech", "DEGREE"),
            ("Computer Science and Engineering", "BRANCH"),
            ("ABC Institute of Technology", "COLLEGE_NAME")
        ]
    },
    {
        "text": "You can contact me at arjun.kumar@example.com or +91 98765 43210.",
        "entities": [
            ("arjun.kumar@example.com", "EMAIL"),
            ("+91 98765 43210", "PHONE")
        ]
    }
]

print("Number of examples:", len(examples))

for example in examples:
    print("\nTEXT:", example["text"])
    print("ENTITIES:", example["entities"])

Number of examples: 4

TEXT: My name is Arjun Kumar and I was born on 18 March 2003.
ENTITIES: [('Arjun Kumar', 'PERSON_NAME'), ('18 March 2003', 'DATE_OF_BIRTH')]

TEXT: I studied at ABC High School under CBSE and passed in 2021 with 92.4%.
ENTITIES: [('ABC High School', 'SCHOOL_NAME'), ('CBSE', 'BOARD'), ('2021', 'YEAR_OF_PASSING'), ('92.4%', 'PERCENTAGE')]

TEXT: I completed my B.Tech in Computer Science and Engineering from ABC Institute of Technology.
ENTITIES: [('B.Tech', 'DEGREE'), ('Computer Science and Engineering', 'BRANCH'), ('ABC Institute of Technology', 'COLLEGE_NAME')]

TEXT: You can contact me at arjun.kumar@example.com or +91 98765 43210.
ENTITIES: [('arjun.kumar@example.com', 'EMAIL'), ('+91 98765 43210', 'PHONE')]

In [ ]:
examples[3] = {
    "text": "You can contact me at arjun.kumar@example.com or +91 98765 43210.",
    "entities": [
        ("arjun.kumar@example.com", "EMAIL"),
        ("+91 98765 43210", "PHONE")
    ]
}

print(examples[3])

{'text': 'You can contact me at arjun.kumar@example.com or +91 98765 43210.', 'entities': [('arjun.kumar@example.com', 'EMAIL'), ('+91 98765 43210', 'PHONE')]}

In [ ]:
examples[3]["text"] = "You can contact me at arjun.kumar@example.com or +91 98765 43210."

examples[3]["entities"] = [
    ("arjun.kumar@example.com", "EMAIL"),
    ("+91 98765 43210", "PHONE")
]

print("TEXT:", examples[3]["text"])
print("ENTITIES:", examples[3]["entities"])

TEXT: You can contact me at arjun.kumar@example.com or +91 98765 43210.
ENTITIES: [('arjun.kumar@example.com', 'EMAIL'), ('+91 98765 43210', 'PHONE')]

In [ ]:
# Replace the email example with a simple phone-only example
examples[3] = {
    "text": "My phone number is +91 98765 43210.",
    "entities": [
        ("+91 98765 43210", "PHONE")
    ]
}

print("TEXT:", examples[3]["text"])
print("ENTITIES:", examples[3]["entities"])

TEXT: My phone number is +91 98765 43210.
ENTITIES: [('+91 98765 43210', 'PHONE')]

In [ ]:
import random

# Different realistic values for our 25 entities
data = {
    "PERSON_NAME": [
        "Arjun Kumar", "Rahul Sharma", "Priya Reddy",
        "Mohammed Sameer", "Ananya Singh", "Vikram Rao"
    ],

    "DATE_OF_BIRTH": [
        "18 March 2003", "12 July 2002", "25 January 2004",
        "03/09/2003", "21-11-2002"
    ],

    "GENDER": [
        "Male", "Female"
    ],

    "NATIONALITY": [
        "Indian", "Indian citizen"
    ],

    "PHONE": [
        "+91 98765 43210", "+91 91234 56789",
        "9876543210", "9123456789"
    ],

    "EMAIL": [
        "arjun@example.com", "rahul@gmail.com",
        "priya123@yahoo.com", "student@college.edu"
    ],

    "ADDRESS": [
        "24 Lake View Road, Vijayawada",
        "12 MG Road, Hyderabad",
        "45 Gandhi Nagar, Bengaluru",
        "8 Park Street, Chennai"
    ],

    "PINCODE": [
        "520010", "500001", "560001", "600001", "110001"
    ],

    "SCHOOL_NAME": [
        "ABC High School", "Sri Chaitanya School",
        "Delhi Public School", "St. Mary's High School"
    ],

    "COLLEGE_NAME": [
        "ABC Institute of Technology",
        "VIT University",
        "SRM Institute of Science and Technology",
        "Andhra University"
    ],

    "DEGREE": [
        "B.Tech", "B.E.", "B.Sc", "M.Tech", "MBA"
    ],

    "BRANCH": [
        "Computer Science and Engineering",
        "Electronics and Communication Engineering",
        "Mechanical Engineering",
        "Electrical Engineering"
    ],

    "BOARD": [
        "CBSE", "ICSE", "Andhra Pradesh Board",
        "Telangana State Board"
    ],

    "YEAR_OF_PASSING": [
        "2020", "2021", "2022", "2023", "2024", "2025"
    ],

    "PERCENTAGE": [
        "85%", "92.4%", "78.5%", "91%", "88.6%"
    ],

    "CGPA": [
        "7.8", "8.4", "9.1", "8.7", "7.5"
    ],

    "ROLL_NUMBER": [
        "12345678", "24CSE1023", "2021A001",
        "EC12345", "98765432"
    ],

    "COMPANY_NAME": [
        "Tech Solutions Pvt Ltd",
        "Infosys",
        "Tata Consultancy Services",
        "Microsoft",
        "ABC Technologies"
    ],

    "JOB_TITLE": [
        "Software Engineering Intern",
        "Software Engineer",
        "Web Developer",
        "Data Analyst",
        "Project Intern"
    ],

    "WORK_LOCATION": [
        "Hyderabad", "Bengaluru", "Chennai",
        "Mumbai", "Pune"
    ],

    "WORK_DURATION": [
        "June 2024 - August 2024",
        "January 2023 - December 2023",
        "6 months",
        "2 years"
    ],

    "SKILL": [
        "Python", "Java", "C++", "SQL",
        "Machine Learning", "HTML", "CSS", "JavaScript"
    ],

    "CERTIFICATION": [
        "AWS Cloud Practitioner",
        "Python Programming Certificate",
        "Google Data Analytics Certificate",
        "Machine Learning Certification"
    ],

    "PROJECT": [
        "Automatic Form-Filling Tool",
        "Student Management System",
        "Online Banking System",
        "Face Recognition System"
    ],

    "ID_NUMBER": [
        "XXXX-XXXX-1234",
        "ID20240123",
        "STU123456",
        "DOC987654"
    ]
}

print("Number of entity types:", len(data))

for label, values in data.items():
    print(label, "→", len(values), "values")

Number of entity types: 25
PERSON_NAME → 6 values
DATE_OF_BIRTH → 5 values
GENDER → 2 values
NATIONALITY → 2 values
PHONE → 4 values
EMAIL → 4 values
ADDRESS → 4 values
PINCODE → 5 values
SCHOOL_NAME → 4 values
COLLEGE_NAME → 4 values
DEGREE → 5 values
BRANCH → 4 values
BOARD → 4 values
YEAR_OF_PASSING → 6 values
PERCENTAGE → 5 values
CGPA → 5 values
ROLL_NUMBER → 5 values
COMPANY_NAME → 5 values
JOB_TITLE → 5 values
WORK_LOCATION → 5 values
WORK_DURATION → 4 values
SKILL → 8 values
CERTIFICATION → 4 values
PROJECT → 4 values
ID_NUMBER → 4 values

In [ ]:
import random

templates = {
    "PERSON_NAME": [
        "My name is {value}.",
        "Full Name: {value}",
        "Student Name: {value}",
        "Candidate: {value}",
        "I am {value}."
    ],

    "DATE_OF_BIRTH": [
        "Date of Birth: {value}",
        "DOB: {value}",
        "I was born on {value}.",
        "Birth date: {value}"
    ],

    "GENDER": [
        "Gender: {value}",
        "Sex: {value}",
        "I am {value}."
    ],

    "NATIONALITY": [
        "Nationality: {value}",
        "I am a {value} citizen.",
        "Country of citizenship: {value}"
    ],

    "PHONE": [
        "Phone: {value}",
        "Mobile number: {value}",
        "Contact number: {value}",
        "You can reach me at {value}."
    ],

    "EMAIL": [
        "Email: {value}",
        "Email address: {value}",
        "Contact me at {value}.",
        "My email is {value}."
    ],

    "ADDRESS": [
        "Address: {value}",
        "Residential address: {value}",
        "I live at {value}.",
        "Permanent address: {value}"
    ],

    "PINCODE": [
        "PIN Code: {value}",
        "Postal Code: {value}",
        "ZIP: {value}",
        "Pincode: {value}"
    ],

    "SCHOOL_NAME": [
        "School Name: {value}",
        "I studied at {value}.",
        "School: {value}",
        "Secondary school: {value}"
    ],

    "COLLEGE_NAME": [
        "College Name: {value}",
        "I studied at {value}.",
        "University: {value}",
        "Institution: {value}"
    ],

    "DEGREE": [
        "Degree: {value}",
        "I completed my {value}.",
        "Qualification: {value}",
        "Course: {value}"
    ],

    "BRANCH": [
        "Branch: {value}",
        "Specialization: {value}",
        "Field of study: {value}",
        "Major: {value}"
    ],

    "BOARD": [
        "Board: {value}",
        "Education board: {value}",
        "I studied under {value}.",
        "Board of education: {value}"
    ],

    "YEAR_OF_PASSING": [
        "Year of Passing: {value}",
        "Passed out in {value}.",
        "Graduation year: {value}",
        "Year completed: {value}"
    ],

    "PERCENTAGE": [
        "Percentage: {value}",
        "I scored {value}.",
        "Marks obtained: {value}",
        "Overall percentage: {value}"
    ],

    "CGPA": [
        "CGPA: {value}",
        "My CGPA is {value}.",
        "Overall CGPA: {value}",
        "I obtained a CGPA of {value}."
    ],

    "ROLL_NUMBER": [
        "Roll Number: {value}",
        "Roll No: {value}",
        "Student Roll Number: {value}",
        "Registration Number: {value}"
    ],

    "COMPANY_NAME": [
        "Company: {value}",
        "I worked at {value}.",
        "Employer: {value}",
        "Organization: {value}"
    ],

    "JOB_TITLE": [
        "Job Title: {value}",
        "Position: {value}",
        "I worked as a {value}.",
        "Designation: {value}"
    ],

    "WORK_LOCATION": [
        "Work Location: {value}",
        "I worked in {value}.",
        "Job location: {value}",
        "Office location: {value}"
    ],

    "WORK_DURATION": [
        "Duration: {value}",
        "I worked there for {value}.",
        "Employment period: {value}",
        "Work period: {value}"
    ],

    "SKILL": [
        "Skill: {value}",
        "Technical skill: {value}",
        "I am skilled in {value}.",
        "Proficient in {value}."
    ],

    "CERTIFICATION": [
        "Certification: {value}",
        "Certificate: {value}",
        "I completed {value}.",
        "Certified in {value}."
    ],

    "PROJECT": [
        "Project: {value}",
        "I worked on {value}.",
        "Project title: {value}",
        "My project was {value}."
    ],

    "ID_NUMBER": [
        "ID Number: {value}",
        "Identification Number: {value}",
        "Document ID: {value}",
        "ID: {value}"
    ]
}

print("Number of template categories:", len(templates))

Number of template categories: 25

In [ ]:
import random

def generate_example():
    # Pick 2–5 different entity types for each example
    num_entities = random.randint(2, 5)
    labels = random.sample(list(data.keys()), num_entities)

    parts = []
    entities = []

    for label in labels:
        value = random.choice(data[label])
        template = random.choice(templates[label])
        sentence = template.format(value=value)

        parts.append(sentence)

        # Store the entity exactly as it appears in the sentence
        entities.append((value, label))

    text = " ".join(parts)

    return {
        "text": text,
        "entities": entities
    }


# Generate 2,000 examples
dataset = [generate_example() for _ in range(2000)]

print("Total examples:", len(dataset))

# Show 5 random examples
print("\n--- SAMPLE EXAMPLES ---")

for example in random.sample(dataset, 5):
    print("\nTEXT:", example["text"])
    print("ENTITIES:", example["entities"])

Total examples: 2000

--- SAMPLE EXAMPLES ---

TEXT: Graduation year: 2024 You can reach me at 9876543210.
ENTITIES: [('2024', 'YEAR_OF_PASSING'), ('9876543210', 'PHONE')]

TEXT: Office location: Hyderabad Job Title: Web Developer Project title: Student Management System Full Name: Vikram Rao
ENTITIES: [('Hyderabad', 'WORK_LOCATION'), ('Web Developer', 'JOB_TITLE'), ('Student Management System', 'PROJECT'), ('Vikram Rao', 'PERSON_NAME')]

TEXT: Job location: Hyderabad I worked as a Project Intern. Certified in AWS Cloud Practitioner.
ENTITIES: [('Hyderabad', 'WORK_LOCATION'), ('Project Intern', 'JOB_TITLE'), ('AWS Cloud Practitioner', 'CERTIFICATION')]

TEXT: Address: 12 MG Road, Hyderabad Board of education: ICSE I am a Indian citizen.
ENTITIES: [('12 MG Road, Hyderabad', 'ADDRESS'), ('ICSE', 'BOARD'), ('Indian', 'NATIONALITY')]

TEXT: ID Number: DOC987654 Organization: ABC Technologies
ENTITIES: [('DOC987654', 'ID_NUMBER'), ('ABC Technologies', 'COMPANY_NAME')]

In [ ]:
!pip install -q datasets

In [ ]:
from datasets import load_dataset

dataset = load_dataset("yashpwr/resume-ner-training-data")

print(dataset)

README.md:   0%|          | 0.00/2.20k [00:00<?, ?B/s]

Warning: You are sending unauthenticated requests to the HF Hub. Please set a HF_TOKEN to enable higher rate limits and faster downloads.
WARNING:huggingface_hub.utils._http:Warning: You are sending unauthenticated requests to the HF Hub. Please set a HF_TOKEN to enable higher rate limits and faster downloads.

data/train-00000-of-00001.parquet: reconstructing file:   0%|          |  0.00B / 61.8MB

data/train-00000-of-00001.parquet: downloading bytes:           |  0.00B

Generating train split:   0%|          | 0/22855 [00:00<?, ? examples/s]

DatasetDict({
    train: Dataset({
        features: ['messages'],
        num_rows: 22855
    })
})

In [ ]:
print(dataset["train"][0])

{'messages': [{'content': 'You are an expert resume assistant. You help users write, critique, and improve their resumes to land their dream job.', 'role': 'system'}, {'content': "Please summarize the following resume:\n\nGENERAL MANAGER/FITNESS DIRECTOR Executive Profile Highly motivated, team oriented professional wants to contribute to your organization utilizing recognized achievements in management, with an emphasis on, employee/customer relations, program implementations, training, and employee development. I have been recognized for my exceptional leadership skills, ability to communicate well, and excellent work ethic. Professional Experience General Manager/Fitness Director December 2013 to Current Company Name City , State Manages and supervise approximately 30 Fitness Club employees. Implements and creates fitness/wellness programs to encourage, reward and offer incentives to members who maintain a regular exercise program. Performs assessments and offers recommendations for a healthier lifestyle. Encourages members to maintain a regular exercise program. Assist, instruct and motivate members by provided knowledge, training principles, and basic information relating to fitness. Develops and promotes active member programs, including corporate wellness and activities to increase the members' feelings to self-worth and accomplishment. Enhances, mentors and develops conducive personal training and group fitness programs. Coordinates fitness center repairs and maintenance. Assist in the lease/purchase agreement of new equipment for the facility. Writes, researches, and analyzes information and data to support position with executive management; prepares policies and procedures for management review; obtains approval; plans and directs from inception to event completion; create and monitors budget; assigns tasks; schedules, markets, and advertises events. Provides mid-level supervisory controls and implements planning, development, evaluation, and promotion of comprehensive fitness center programs and services; researches and develops new programs, classes, operating policies and procedures, and revenue/marketing sources for a variety of fitness, health, leisure, recreational, cultural and sports programs. Works closely with sales and marketing team to generate sales initiatives through social media and grass roots marketing. Monitors daily sales activities and meets with management team regularly to provide updates on sales and promotions. Performs various other duties and assignments as necessary or required. Assistant Manager Educator lululemon athletica October 2012 to December 2014 Company Name City , State Present on the retail floor, as Floor Manager and Educator, for 75% of working hours. Educated guests on our product, community and culture Community and events liaison coordinating events through Metro Atlanta. Oversee the execution of certain deliverables on the manager checklist to include inventory, product and/or community education. Created daily strategies to meet daily, weekly, monthly and quarterly revenue goals; presented forecast numbers to meet hourly and headcount goals Represented the store at all required meetings and conferences. Hands-on roll in the development and a coach to Educators & Key Leaders. Performed personnel reviews and evaluations according to schedule and submitted any subsequent change notices in a timely manner. Performed and completed other additional projects, duties, and assignments.as required and/or by request, under the direction of the Store Manager Advocate for lululemon athletica's values. General Manager June 2007 to October 2012 Company Name City , State Supervised 13 personnel of in all aspects relating to club operation: Coordinated schedules and keeps accurate records of attendance and absences. Provided guidance, training and motivation to staff. Conducted regular staff meetings. Monitored and evaluated work performance of all personnel. Created and maintained positive work environment within the facility. Managed budget with revenue of $950K and expenses not exceeding $620K exceeding budgeted goals. Prepared and provided accurate financial information to the corporate office and university in a timely manner. Solicits prospective corporate and individual members to add to the current membership base of over 1500. Provided information to prospective members regarding club facilities, programs, membership procedures and pricing policies. Conducted regular, creative sales activities. Encouraged members to maintain a regular exercise program. Assists, instructs and motivates members. Provided knowledge, training principles, and basic information relating to fitness. Developed and promoted active member programs and activities to increase the members' feelings to self-worth and accomplishment. Approved all health club related bills received: forwarded approved documents to corporate in a timely manner. Provided accurate personnel and payroll information to corporate in a timely manner, including payroll data for independent contractors (aerobic instructors, personal trainers, massage therapists). Performed personnel reviews and evaluations according to schedule and submitted any subsequent change notices in a timely manner. Maintained cleanliness, operation and safety of club facilities and equipment. Ensured that all duties assigned to assistant manger, wellness coordinator and fitness associates were performed in accordance with corporate CSU standards. Performed various other duties and assignments as necessary or required. Fitness Coordinator March 2006 to June 2007 Company Name City , State Responsible for coordinating group exercise programs for approximately 600 employees, creating monthly schedules, recruiting new instructors, organizing specialty classes, conducting evaluations and creating annual surveys. Supervises 3 Fitness Specialists and oversees the entire fitness area in compliance with ACSM guidelines, completes appointment book for scheduling, delegates responsibilities, monitors floor coverage and facilitates quarterly in house trainings. Responsible for creating company wide monthly newsletter and weekly fit tip, oversees content on company wide website, generates incentive programs and fitness challenges. Speak and facilitate health, fitness and wellness presentations to onsite and offsite employees and contractors. Assists in the delivery of health promotion programs (seminars, health fairs, wellness tables, promotional tables, screening, etc.) Accountable for the internship program, contacting schools, interviewing potential candidates, creating assignments and evaluating interns. Conducts group exercise classes, fitness assessments using ACSM guidelines, program sessions, equipment and new member orientations. Submits bi-weekly payroll for 6 group exercise instructors and monthly group exercise totals and averages for 15 classes. Assists with daily administrative duties, clean and check equipment for any issues and/or problems. Owner/Instructor March 2004 to May 2005 Company Name City , State Owned and operated aerobic studio which offered 8 to 10 fitness classes daily. Conducted the scheduled classes and managed a staff of 5 certified instructors. Responsible for the general maintenance and repairs of the business and equipment. Fully responsible for all physical and financial aspects of the studio. Attended community, city council and business owners meetings on a monthly basis. Responsible for the entire studio's advertising and marketing. Managed an annual budget of $45K. Wellness Director & Aerobic Coordinator July 2001 to February 2004 Company Name City , State Managed and supervised the Wellness Department which consisted of approximately 30 employees. Managed 30 group fitness classes and over 25 fitness assessment appointments. Implemented and evaluated new classes, adult and youth programs, enforced rules and regulations. Prepared annual departmental budget of $230K, to include expenses, fundraising and gift giving. Responsible for employees monthly payroll, pay raises, annual reviews, disciplining, training and development. Coordinated fitness center repairs and maintenance. Assisted in the lease/purchase agreement of new equipment for the facility. Participated in monthly staff and cabinet meetings. Actively motivated staff through positive team building activities and attitude. Lead and developed a member response team through adhering to member suggestions and member appreciation events. Receive Character Development Award - 2002. Corporate Fitness Manager/Director February 1999 to February 2007 Company Name City , State Responsible for implementing and coordinating group exercise programs, personal training sessions, and wellness related activities for over 25 major corporations and universities. Supervises over 325 group fitness classes a week, 120 Exercise Leaders and 4 Area Directors. Manages an annual operating payroll budget of over $300K, prepare and collect monthly receivables. Prepares audit material for annual workers compensation and liability insurance estimates. Responsible for the company recruiting, advertising, and marketing. Club Manager/Fitness Coordinator September 1997 to February 1999 Company Name City , State Established and maintained member relations from sales to member services. Coordinated and taught approximately 6 aerobic classes, implemented training programs for both instructors and members. Responsible for club appearance and maintenance. Processed daily sales log calculations and bi-weekly payrolls. Education BS : Holistic Nutrition , 2010 Clayton College of Natural Health Holistic Nutrition Accounting & Management Human Resources , 1992 California State University Accounting & Management Human Resources Skills Microsoft Windows, Microsoft PowerPoint, Microsoft Outlook, Microsoft Access, SKILLS Internet Explorer and social media", 'role': 'user'}, {'content': 'The candidate is a highly motivated General Manager and Fitness Director with extensive experience in managing fitness centers and implementing wellness programs. With a BS in Holistic Nutrition and a background in human resources and management, they have demonstrated exceptional leadership skills and a strong work ethic throughout their career. Currently overseeing 30 employees, they have successfully developed fitness programs and initiatives that enhance member engagement and satisfaction. Their previous roles include managing budgets, coordinating group exercise programs, and driving sales initiatives across various organizations.', 'role': 'assistant'}]}

In [ ]:
from datasets import load_dataset

conll = load_dataset("tner/conll2003")

print(conll)

README.md:   0%|          | 0.00/2.97k [00:00<?, ?B/s]

conll2003.py:   0%|          | 0.00/2.74k [00:00<?, ?B/s]

RuntimeError: Dataset scripts are no longer supported, but found conll2003.py

In [ ]:
from datasets import load_dataset

conll = load_dataset("lhoestq/conll2003")

print(conll)

dataset_infos.json:   0%|          | 0.00/3.67k [00:00<?, ?B/s]

data/train-00000-of-00001.parquet: reconstructing file:   0%|          |  0.00B / 1.07MB

data/train-00000-of-00001.parquet: downloading bytes:           |  0.00B

data/validation-00000-of-00001.parquet: reconstructing file:   0%|          |  0.00B /  281kB

data/validation-00000-of-00001.parquet: downloading bytes:           |  0.00B

data/test-00000-of-00001.parquet: reconstructing file:   0%|          |  0.00B /  259kB

data/test-00000-of-00001.parquet: downloading bytes:           |  0.00B

Generating train split:   0%|          | 0/14041 [00:00<?, ? examples/s]

Generating validation split:   0%|          | 0/3250 [00:00<?, ? examples/s]

Generating test split:   0%|          | 0/3453 [00:00<?, ? examples/s]

DatasetDict({
    train: Dataset({
        features: ['id', 'tokens', 'pos_tags', 'chunk_tags', 'ner_tags'],
        num_rows: 14041
    })
    validation: Dataset({
        features: ['id', 'tokens', 'pos_tags', 'chunk_tags', 'ner_tags'],
        num_rows: 3250
    })
    test: Dataset({
        features: ['id', 'tokens', 'pos_tags', 'chunk_tags', 'ner_tags'],
        num_rows: 3453
    })
})

In [ ]:
print(conll["train"].features["ner_tags"])

List(Value('int64'))

In [ ]:
print(conll["train"].features["ner_tags"].feature)

Value('int64')

In [ ]:
example = conll["train"][0]

print("TOKENS:")
print(example["tokens"])

print("\nNER TAG IDs:")
print(example["ner_tags"])

TOKENS:
['EU', 'rejects', 'German', 'call', 'to', 'boycott', 'British', 'lamb', '.']

NER TAG IDs:
[3, 0, 7, 0, 0, 0, 7, 0, 0]

In [ ]:
label_names = [
    "O",
    "B-PER",
    "I-PER",
    "B-ORG",
    "I-ORG",
    "B-LOC",
    "I-LOC",
    "B-MISC",
    "I-MISC"
]

example = conll["train"][0]

for token, tag_id in zip(example["tokens"], example["ner_tags"]):
    print(f"{token:15} -> {label_names[tag_id]}")

EU              -> B-ORG
rejects         -> O
German          -> B-MISC
call            -> O
to              -> O
boycott         -> O
British         -> B-MISC
lamb            -> O
.               -> O

In [ ]:
from datasets import load_dataset

resume_ner = load_dataset("oksomu/resume-ner")

print(resume_ner)

DatasetNotFoundError: Dataset 'oksomu/resume-ner' doesn't exist on the Hub or cannot be accessed.

In [ ]:
!pip install -q transformers evaluate seqeval accelerate

     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 43.6/43.6 kB 1.2 MB/s eta 0:00:00
  error: subprocess-exited-with-error

  × python setup.py egg_info did not run successfully.
  │ exit code: 1
  ╰─> See above for output.

  note: This error originates from a subprocess, and is likely not a problem with pip.
  Preparing metadata (setup.py) ... error
error: metadata-generation-failed

× Encountered error while generating package metadata.
╰─> See above for output.

note: This is an issue with the package mentioned above, not pip.
hint: See above for details.

In [ ]:
!pip install -q transformers accelerate seqeval

  error: subprocess-exited-with-error

  × python setup.py egg_info did not run successfully.
  │ exit code: 1
  ╰─> See above for output.

  note: This error originates from a subprocess, and is likely not a problem with pip.
  Preparing metadata (setup.py) ... error
error: metadata-generation-failed

× Encountered error while generating package metadata.
╰─> See above for output.

note: This is an issue with the package mentioned above, not pip.
hint: See above for details.

In [ ]:
!pip install -q --upgrade pip setuptools wheel

   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 1.8/1.8 MB 20.6 MB/s eta 0:00:00
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 818.2/818.2 kB 16.8 MB/s eta 0:00:00
ERROR: pip's dependency resolver does not currently take into account all the packages that are installed. This behaviour is the source of the following dependency conflicts.
ipython 7.34.0 requires jedi>=0.16, which is not installed.
torch 2.11.0+cpu requires setuptools<82, but you have setuptools 84.0.0 which is incompatible.

In [ ]:
!pip install -q "setuptools<82"

In [ ]:
import torch
import transformers
import seqeval

print("PyTorch:", torch.__version__)
print("Transformers:", transformers.__version__)
print("GPU available:", torch.cuda.is_available())
print("Libraries loaded successfully!")

ModuleNotFoundError: No module named 'seqeval'

In [ ]:
import torch
import transformers

print("PyTorch:", torch.__version__)
print("Transformers:", transformers.__version__)
print("GPU available:", torch.cuda.is_available())
print("Setup working!")

PyTorch: 2.11.0+cpu
Transformers: 5.16.1
GPU available: False
Setup working!

In [ ]:
print(dataset["train"].features)

NameError: name 'dataset' is not defined

In [ ]:
from datasets import load_dataset

dataset = load_dataset("yashpwr/resume-ner-training-data")

print(dataset)

Warning: You are sending unauthenticated requests to the HF Hub. Please set a HF_TOKEN to enable higher rate limits and faster downloads.
WARNING:huggingface_hub.utils._http:Warning: You are sending unauthenticated requests to the HF Hub. Please set a HF_TOKEN to enable higher rate limits and faster downloads.

README.md:   0%|          | 0.00/2.20k [00:00<?, ?B/s]

data/train-00000-of-00001.parquet: reconstructing file:   0%|          |  0.00B / 61.8MB

data/train-00000-of-00001.parquet: downloading bytes:           |  0.00B

Generating train split:   0%|          | 0/22855 [00:00<?, ? examples/s]

DatasetDict({
    train: Dataset({
        features: ['messages'],
        num_rows: 22855
    })
})

In [ ]:
from datasets import load_dataset

dataset = load_dataset("lhoestq/conll2003")

print(dataset)
print(dataset["train"].features)

dataset_infos.json:   0%|          | 0.00/3.67k [00:00<?, ?B/s]

data/train-00000-of-00001.parquet: reconstructing file:   0%|          |  0.00B / 1.07MB

data/train-00000-of-00001.parquet: downloading bytes:           |  0.00B

data/validation-00000-of-00001.parquet: reconstructing file:   0%|          |  0.00B /  281kB

data/validation-00000-of-00001.parquet: downloading bytes:           |  0.00B

data/test-00000-of-00001.parquet: reconstructing file:   0%|          |  0.00B /  259kB

data/test-00000-of-00001.parquet: downloading bytes:           |  0.00B

Generating train split:   0%|          | 0/14041 [00:00<?, ? examples/s]

Generating validation split:   0%|          | 0/3250 [00:00<?, ? examples/s]

Generating test split:   0%|          | 0/3453 [00:00<?, ? examples/s]

DatasetDict({
    train: Dataset({
        features: ['id', 'tokens', 'pos_tags', 'chunk_tags', 'ner_tags'],
        num_rows: 14041
    })
    validation: Dataset({
        features: ['id', 'tokens', 'pos_tags', 'chunk_tags', 'ner_tags'],
        num_rows: 3250
    })
    test: Dataset({
        features: ['id', 'tokens', 'pos_tags', 'chunk_tags', 'ner_tags'],
        num_rows: 3453
    })
})
{'id': Value('string'), 'tokens': List(Value('string')), 'pos_tags': List(Value('int64')), 'chunk_tags': List(Value('int64')), 'ner_tags': List(Value('int64'))}

In [ ]:
id2label = {
    0: "O",
    1: "B-PER",
    2: "I-PER",
    3: "B-ORG",
    4: "I-ORG",
    5: "B-LOC",
    6: "I-LOC",
    7: "B-MISC",
    8: "I-MISC"
}

label2id = {v: k for k, v in id2label.items()}

print(id2label)
print(label2id)

{0: 'O', 1: 'B-PER', 2: 'I-PER', 3: 'B-ORG', 4: 'I-ORG', 5: 'B-LOC', 6: 'I-LOC', 7: 'B-MISC', 8: 'I-MISC'}
{'O': 0, 'B-PER': 1, 'I-PER': 2, 'B-ORG': 3, 'I-ORG': 4, 'B-LOC': 5, 'I-LOC': 6, 'B-MISC': 7, 'I-MISC': 8}

In [ ]:
from transformers import AutoTokenizer

model_name = "distilbert-base-cased"

tokenizer = AutoTokenizer.from_pretrained(model_name)

print("Tokenizer loaded successfully!")

config.json:   0%|          | 0.00/465 [00:00<?, ?B/s]

tokenizer_config.json:   0%|          | 0.00/49.0 [00:00<?, ?B/s]

vocab.txt:   0%|          | 0.00/213k [00:00<?, ?B/s]

tokenizer.json:   0%|          | 0.00/436k [00:00<?, ?B/s]

Tokenizer loaded successfully!

In [ ]:
def tokenize_and_align_labels(examples):
    tokenized = tokenizer(
        examples["tokens"],
        truncation=True,
        is_split_into_words=True
    )

    all_labels = []

    for i, labels in enumerate(examples["ner_tags"]):
        word_ids = tokenized.word_ids(batch_index=i)
        previous_word_id = None
        label_ids = []

        for word_id in word_ids:
            if word_id is None:
                label_ids.append(-100)
            elif word_id != previous_word_id:
                label_ids.append(labels[word_id])
            else:
                label_ids.append(-100)

            previous_word_id = word_id

        all_labels.append(label_ids)

    tokenized["labels"] = all_labels
    return tokenized


tokenized_dataset = dataset.map(
    tokenize_and_align_labels,
    batched=True
)

print(tokenized_dataset)

Map:   0%|          | 0/14041 [00:00<?, ? examples/s]

Map:   0%|          | 0/3250 [00:00<?, ? examples/s]

Map:   0%|          | 0/3453 [00:00<?, ? examples/s]

DatasetDict({
    train: Dataset({
        features: ['id', 'tokens', 'pos_tags', 'chunk_tags', 'ner_tags', 'input_ids', 'token_type_ids', 'attention_mask', 'labels'],
        num_rows: 14041
    })
    validation: Dataset({
        features: ['id', 'tokens', 'pos_tags', 'chunk_tags', 'ner_tags', 'input_ids', 'token_type_ids', 'attention_mask', 'labels'],
        num_rows: 3250
    })
    test: Dataset({
        features: ['id', 'tokens', 'pos_tags', 'chunk_tags', 'ner_tags', 'input_ids', 'token_type_ids', 'attention_mask', 'labels'],
        num_rows: 3453
    })
})

In [ ]:
from transformers import AutoModelForTokenClassification

model = AutoModelForTokenClassification.from_pretrained(
    model_name,
    num_labels=len(id2label),
    id2label=id2label,
    label2id=label2id
)

print("NER model loaded successfully!")

model.safetensors: reconstructing file:   0%|          |  0.00B /  263MB

model.safetensors: downloading bytes:           |  0.00B

Loading weights:   0%|          | 0/100 [00:00<?, ?it/s]

[transformers] DistilBertForTokenClassification LOAD REPORT from: distilbert-base-cased
Key                     | Status     |
------------------------+------------+-
vocab_layer_norm.bias   | UNEXPECTED |
vocab_transform.bias    | UNEXPECTED |
vocab_layer_norm.weight | UNEXPECTED |
vocab_projector.bias    | UNEXPECTED |
vocab_transform.weight  | UNEXPECTED |
classifier.weight       | MISSING    |
classifier.bias         | MISSING    |

Notes:
- UNEXPECTED:	can be ignored when loading from different task/architecture; not ok if you expect identical arch.
- MISSING:	those params were newly initialized because missing from the checkpoint. Consider training on your downstream task.

NER model loaded successfully!

In [ ]:
from transformers import DataCollatorForTokenClassification

data_collator = DataCollatorForTokenClassification(
    tokenizer=tokenizer
)

print("Data collator ready!")

Data collator ready!

In [ ]:
NER_LABELS = [
    "O",
    "B-PERSON_NAME", "I-PERSON_NAME",
    "B-DATE_OF_BIRTH", "I-DATE_OF_BIRTH",
    "B-GENDER", "I-GENDER",
    "B-NATIONALITY", "I-NATIONALITY",
    "B-PHONE", "I-PHONE",
    "B-EMAIL", "I-EMAIL",
    "B-ADDRESS", "I-ADDRESS",
    "B-PINCODE", "I-PINCODE",
    "B-SCHOOL_NAME", "I-SCHOOL_NAME",
    "B-COLLEGE_NAME", "I-COLLEGE_NAME",
    "B-DEGREE", "I-DEGREE",
    "B-BRANCH", "I-BRANCH",
    "B-BOARD", "I-BOARD",
    "B-YEAR_OF_PASSING", "I-YEAR_OF_PASSING",
    "B-PERCENTAGE", "I-PERCENTAGE",
    "B-CGPA", "I-CGPA",
    "B-ROLL_NUMBER", "I-ROLL_NUMBER",
    "B-COMPANY_NAME", "I-COMPANY_NAME",
    "B-JOB_TITLE", "I-JOB_TITLE",
    "B-WORK_LOCATION", "I-WORK_LOCATION",
    "B-WORK_DURATION", "I-WORK_DURATION",
    "B-SKILL", "I-SKILL",
    "B-CERTIFICATION", "I-CERTIFICATION",
    "B-PROJECT", "I-PROJECT",
    "B-ID_NUMBER", "I-ID_NUMBER"
]

label2id = {label: i for i, label in enumerate(NER_LABELS)}
id2label = {i: label for i, label in enumerate(NER_LABELS)}

print("Total labels:", len(NER_LABELS))

Total labels: 51

In [ ]:
import random

examples = []

for _ in range(2000):
    name = random.choice(["Rahman Shaik", "Arjun Kumar", "Priya Sharma", "Aisha Khan"])
    email = random.choice(["rahman@gmail.com", "arjun@gmail.com", "priya@gmail.com"])
    phone = random.choice(["9876543210", "9123456780", "9988776655"])
    degree = random.choice(["B.Tech", "BCA", "M.Tech", "MBA"])
    branch = random.choice(["Computer Science", "Electronics", "Information Technology"])
    college = random.choice(["ABC College", "XYZ University", "National Institute of Technology"])
    company = random.choice(["TCS", "Infosys", "Microsoft", "Google"])
    skill = random.choice(["Python", "Java", "SQL", "Machine Learning"])

    text = (
        f"My name is {name}. "
        f"My email is {email}. "
        f"My phone number is {phone}. "
        f"I completed {degree} in {branch} from {college}. "
        f"I worked at {company}. "
        f"My skills include {skill}."
    )

    examples.append({
        "text": text,
        "entities": [
            [text.index(name), text.index(name) + len(name), "PERSON_NAME"],
            [text.index(email), text.index(email) + len(email), "EMAIL"],
            [text.index(phone), text.index(phone) + len(phone), "PHONE"],
            [text.index(degree), text.index(degree) + len(degree), "DEGREE"],
            [text.index(branch), text.index(branch) + len(branch), "BRANCH"],
            [text.index(college), text.index(college) + len(college), "COLLEGE_NAME"],
            [text.index(company), text.index(company) + len(company), "COMPANY_NAME"],
            [text.index(skill), text.index(skill) + len(skill), "SKILL"]
        ]
    ])

print("Examples created:", len(examples))
print(examples[0])

SyntaxError: closing parenthesis ']' does not match opening parenthesis '{' on line 24 (3019297673.py, line 36)

In [ ]:
import random

examples = []

for _ in range(2000):
    name = random.choice([
        "Rahman Shaik", "Arjun Kumar", "Priya Sharma", "Aisha Khan"
    ])
    email = random.choice([
        "rahman@gmail.com", "arjun@gmail.com",
        "priya@gmail.com", "aisha@gmail.com"
    ])
    phone = random.choice([
        "9876543210", "9123456780", "9988776655"
    ])
    degree = random.choice(["B.Tech", "BCA", "M.Tech", "MBA"])
    branch = random.choice([
        "Computer Science", "Electronics", "Information Technology"
    ])
    college = random.choice([
        "ABC College", "XYZ University",
        "National Institute of Technology"
    ])
    company = random.choice([
        "TCS", "Infosys", "Microsoft", "Google"
    ])
    skill = random.choice([
        "Python", "Java", "SQL", "Machine Learning"
    ])

    text = (
        f"My name is {name}. "
        f"My email is {email}. "
        f"My phone number is {phone}. "
        f"I completed {degree} in {branch} from {college}. "
        f"I worked at {company}. "
        f"My skills include {skill}."
    )

    entities = [
        [text.index(name), text.index(name) + len(name), "PERSON_NAME"],
        [text.index(email), text.index(email) + len(email), "EMAIL"],
        [text.index(phone), text.index(phone) + len(phone), "PHONE"],
        [text.index(degree), text.index(degree) + len(degree), "DEGREE"],
        [text.index(branch), text.index(branch) + len(branch), "BRANCH"],
        [text.index(college), text.index(college) + len(college), "COLLEGE_NAME"],
        [text.index(company), text.index(company) + len(company), "COMPANY_NAME"],
        [text.index(skill), text.index(skill) + len(skill), "SKILL"]
    ]

    examples.append({
        "text": text,
        "entities": entities
    })

print("Examples created:", len(examples))
print(examples[0])

Examples created: 2000
{'text': 'My name is Priya Sharma. My email is rahman@gmail.com. My phone number is 9123456780. I completed MBA in Computer Science from XYZ University. I worked at TCS. My skills include Python.', 'entities': [[11, 23, 'PERSON_NAME'], [37, 53, 'EMAIL'], [74, 84, 'PHONE'], [98, 101, 'DEGREE'], [105, 121, 'BRANCH'], [127, 141, 'COLLEGE_NAME'], [155, 158, 'COMPANY_NAME'], [178, 184, 'SKILL']]}

In [ ]:
import re

for example in examples:
    example["text"] = re.sub(
        r'\[([^\]]+)\]\(mailto:[^)]+\)',
        r'\1',
        example["text"]
    )

print(examples[0])

{'text': 'My name is Priya Sharma. My email is rahman@gmail.com. My phone number is 9123456780. I completed MBA in Computer Science from XYZ University. I worked at TCS. My skills include Python.', 'entities': [[11, 23, 'PERSON_NAME'], [37, 53, 'EMAIL'], [74, 84, 'PHONE'], [98, 101, 'DEGREE'], [105, 121, 'BRANCH'], [127, 141, 'COLLEGE_NAME'], [155, 158, 'COMPANY_NAME'], [178, 184, 'SKILL']]}

In [ ]:
for example in examples:
    text = example["text"]

    # Remove Markdown email formatting
    match = re.search(r'\[([^\]]+)\]\(mailto\\?:([^)]+)\)', text)

    if match:
        email = match.group(1)
        old = match.group(0)
        text = text.replace(old, email)

        # Rebuild entity positions after cleaning
        entities = []
        for start, end, label in example["entities"]:
            entity_text = example["text"][start:end]

            if entity_text.startswith("["):
                entity_text = email

            new_start = text.find(entity_text)

            if new_start != -1:
                entities.append([
                    new_start,
                    new_start + len(entity_text),
                    label
                ])

        example["text"] = text
        example["entities"] = entities

print(examples[0])

{'text': 'My name is Priya Sharma. My email is rahman@gmail.com. My phone number is 9123456780. I completed MBA in Computer Science from XYZ University. I worked at TCS. My skills include Python.', 'entities': [[11, 23, 'PERSON_NAME'], [37, 53, 'EMAIL'], [74, 84, 'PHONE'], [98, 101, 'DEGREE'], [105, 121, 'BRANCH'], [127, 141, 'COLLEGE_NAME'], [155, 158, 'COMPANY_NAME'], [178, 184, 'SKILL']]}

In [ ]:
!wget -q "https://www.kaggle.com/api/v1/datasets/download/dataturks/resume-entities-for-ner" -O dataturks.zip
!unzip -o dataturks.zip
!ls -lh

Archive:  dataturks.zip
  inflating: Entity Recognition in Resumes.json
total 1.5M
-rw-r--r-- 1 root root 323K Oct  2  2019  dataturks.zip
-rw-r--r-- 1 root root 1.2M Oct  2  2019 'Entity Recognition in Resumes.json'
drwxr-xr-x 1 root root 4.0K Sep  4 13:25  sample_data

In [ ]:
import json

with open("Entity Recognition in Resumes.json", "r", encoding="utf-8") as f:
    data = json.load(f)

print("Number of resumes:", len(data))
print("\nFirst resume:")
print(json.dumps(data[0], indent=2)[:5000])

JSONDecodeError: Extra data: line 2 column 1 (char 3520)

In [ ]:
import json

data = []

with open("Entity Recognition in Resumes.json", "r", encoding="utf-8") as f:
    for line in f:
        line = line.strip()
        if line:
            data.append(json.loads(line))

print("Number of resumes:", len(data))
print("\nFirst resume:")
print(json.dumps(data[0], indent=2)[:5000])

Number of resumes: 220

First resume:
{
  "content": "Abhishek Jha\nApplication Development Associate - Accenture\n\nBengaluru, Karnataka - Email me on Indeed: indeed.com/r/Abhishek-Jha/10e7a8cb732bc43a\n\n\u2022 To work for an organization which provides me the opportunity to improve my skills\nand knowledge for my individual and company's growth in best possible ways.\n\nWilling to relocate to: Bangalore, Karnataka\n\nWORK EXPERIENCE\n\nApplication Development Associate\n\nAccenture -\n\nNovember 2017 to Present\n\nRole: Currently working on Chat-bot. Developing Backend Oracle PeopleSoft Queries\nfor the Bot which will be triggered based on given input. Also, Training the bot for different possible\nutterances (Both positive and negative), which will be given as\ninput by the user.\n\nEDUCATION\n\nB.E in Information science and engineering\n\nB.v.b college of engineering and technology -  Hubli, Karnataka\n\nAugust 2013 to June 2017\n\n12th in Mathematics\n\nWoodbine modern school\n\nApril 2011 to March 2013\n\n10th\n\nKendriya Vidyalaya\n\nApril 2001 to March 2011\n\nSKILLS\n\nC (Less than 1 year), Database (Less than 1 year), Database Management (Less than 1 year),\nDatabase Management System (Less than 1 year), Java (Less than 1 year)\n\nADDITIONAL INFORMATION\n\nTechnical Skills\n\nhttps://www.indeed.com/r/Abhishek-Jha/10e7a8cb732bc43a?isid=rex-download&ikw=download-top&co=IN\n\n\n\u2022 Programming language: C, C++, Java\n\u2022 Oracle PeopleSoft\n\u2022 Internet Of Things\n\u2022 Machine Learning\n\u2022 Database Management System\n\u2022 Computer Networks\n\u2022 Operating System worked on: Linux, Windows, Mac\n\nNon - Technical Skills\n\n\u2022 Honest and Hard-Working\n\u2022 Tolerant and Flexible to Different Situations\n\u2022 Polite and Calm\n\u2022 Team-Player",
  "annotation": [
    {
      "label": [
        "Skills"
      ],
      "points": [
        {
          "start": 1295,
          "end": 1621,
          "text": "\n\u2022 Programming language: C, C++, Java\n\u2022 Oracle PeopleSoft\n\u2022 Internet Of Things\n\u2022 Machine Learning\n\u2022 Database Management System\n\u2022 Computer Networks\n\u2022 Operating System worked on: Linux, Windows, Mac\n\nNon - Technical Skills\n\n\u2022 Honest and Hard-Working\n\u2022 Tolerant and Flexible to Different Situations\n\u2022 Polite and Calm\n\u2022 Team-Player"
        }
      ]
    },
    {
      "label": [
        "Skills"
      ],
      "points": [
        {
          "start": 993,
          "end": 1153,
          "text": "C (Less than 1 year), Database (Less than 1 year), Database Management (Less than 1 year),\nDatabase Management System (Less than 1 year), Java (Less than 1 year)"
        }
      ]
    },
    {
      "label": [
        "College Name"
      ],
      "points": [
        {
          "start": 939,
          "end": 956,
          "text": "Kendriya Vidyalaya"
        }
      ]
    },
    {
      "label": [
        "College Name"
      ],
      "points": [
        {
          "start": 883,
          "end": 904,
          "text": "Woodbine modern school"
        }
      ]
    },
    {
      "label": [
        "Graduation Year"
      ],
      "points": [
        {
          "start": 856,
          "end": 860,
          "text": "2017\n"
        }
      ]
    },
    {
      "label": [
        "College Name"
      ],
      "points": [
        {
          "start": 771,
          "end": 813,
          "text": "B.v.b college of engineering and technology"
        }
      ]
    },
    {
      "label": [
        "Designation"
      ],
      "points": [
        {
          "start": 727,
          "end": 769,
          "text": "B.E in Information science and engineering\n"
        }
      ]
    },
    {
      "label": [
        "Companies worked at"
      ],
      "points": [
        {
          "start": 407,
          "end": 415,
          "text": "Accenture"
        }
      ]
    },
    {
      "label": [
        "Designation"
      ],
      "points": [
        {
          "start": 372,
          "end": 404,
          "text": "Application Development Associate"
        }
      ]
    },
    {
      "label": [
        "Email Address"
      ],
      "points": [
        {
          "start": 95,
          "end": 145,
          "text": "Indeed: indeed.com/r/Abhishek-Jha/10e7a8cb732bc43a\n"
        }
      ]
    },
    {
      "label": [
        "Location"
      ],
      "points": [
        {
          "start": 60,
          "end": 68,
          "text": "Bengaluru"
        }
      ]
    },
    {
      "label": [
        "Companies worked at"
      ],
      "points": [
        {
          "start": 49,
          "end": 57,
          "text": "Accenture"
        }
      ]
    },
    {
      "label": [
        "Designation"
      ],
      "points": [
        {
          "start": 13,
          "end": 45,
          "text": "Application Development Associate"
        }
      ]
    },
    {
      "label": [
        "Name"
      ],
      "points": [
        {
          "start": 0,

In [ ]:
from collections import Counter

label_counts = Counter()

for resume in data:
    for annotation in resume["annotation"]:
        label = annotation["label"][0]
        label_counts[label] += 1

print("Available labels:")
for label, count in label_counts.most_common():
    print(f"{label}: {count}")

IndexError: list index out of range

In [ ]:
from collections import Counter

label_counts = Counter()

for resume in data:
    for annotation in resume["annotation"]:
        if annotation.get("label"):
            label = annotation["label"][0]
            label_counts[label] += 1

print("Available labels:")
for label, count in label_counts.most_common():
    print(f"{label}: {count}")

Available labels:
Companies worked at: 729
Designation: 521
Skills: 472
Location: 430
College Name: 330
Degree: 298
Graduation Year: 254
Email Address: 252
Name: 224
Years of Experience: 44
UNKNOWN: 2

In [ ]:
NER_LABELS = [
    "O",
    "B-NAME", "I-NAME",
    "B-EMAIL", "I-EMAIL",
    "B-PHONE", "I-PHONE",
    "B-LOCATION", "I-LOCATION",
    "B-COMPANY", "I-COMPANY",
    "B-DESIGNATION", "I-DESIGNATION",
    "B-COLLEGE", "I-COLLEGE",
    "B-DEGREE", "I-DEGREE",
    "B-GRADUATION_YEAR", "I-GRADUATION_YEAR",
    "B-SKILL", "I-SKILL",
    "B-EXPERIENCE", "I-EXPERIENCE"
]

label2id = {label: i for i, label in enumerate(NER_LABELS)}
id2label = {i: label for i, label in enumerate(NER_LABELS)}

print("Total BIO labels:", len(NER_LABELS))

Total BIO labels: 23

In [ ]:
def convert_to_bio(resume):
    text = resume["content"]
    annotations = []

    label_map = {
        "Name": "NAME",
        "Email Address": "EMAIL",
        "Location": "LOCATION",
        "Companies worked at": "COMPANY",
        "Designation": "DESIGNATION",
        "College Name": "COLLEGE",
        "Degree": "DEGREE",
        "Graduation Year": "GRADUATION_YEAR",
        "Skills": "SKILL",
        "Years of Experience": "EXPERIENCE"
    }

    for ann in resume["annotation"]:
        if not ann.get("label"):
            continue

        original_label = ann["label"][0]

        if original_label not in label_map:
            continue

        label = label_map[original_label]

        for point in ann.get("points", []):
            start = point["start"]
            end = point["end"]

            annotations.append((start, end, label))

    annotations.sort(key=lambda x: x[0])

    words = []
    current_word = ""
    word_start = None

    for i, char in enumerate(text):
        if char.isspace():
            if current_word:
                words.append((current_word, word_start, i))
                current_word = ""
                word_start = None
        else:
            if current_word == "":
                word_start = i
            current_word += char

    if current_word:
        words.append((current_word, word_start, len(text)))

    bio_labels = []

    for word, start, end in words:
        label = "O"

        for ent_start, ent_end, ent_label in annotations:
            if start >= ent_start and end <= ent_end:
                if start == ent_start:
                    label = "B-" + ent_label
                else:
                    label = "I-" + ent_label
                break

        bio_labels.append(label)

    return {
        "tokens": [w[0] for w in words],
        "ner_tags": [label2id[x] for x in bio_labels]
    }


bio_data = [convert_to_bio(resume) for resume in data]

print("Converted resumes:", len(bio_data))
print("\nFirst example:")
print(bio_data[0]["tokens"][:30])
print(bio_data[0]["ner_tags"][:30])

Converted resumes: 220

First example:
['Abhishek', 'Jha', 'Application', 'Development', 'Associate', '-', 'Accenture', 'Bengaluru,', 'Karnataka', '-', 'Email', 'me', 'on', 'Indeed:', 'indeed.com/r/Abhishek-Jha/10e7a8cb732bc43a', '•', 'To', 'work', 'for', 'an', 'organization', 'which', 'provides', 'me', 'the', 'opportunity', 'to', 'improve', 'my', 'skills']
[1, 0, 11, 12, 0, 0, 0, 0, 0, 0, 0, 0, 0, 3, 4, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0]

In [ ]:
from collections import Counter

bio_counts = Counter()

for example in bio_data:
    for tag_id in example["ner_tags"]:
        bio_counts[id2label[tag_id]] += 1

for label, count in bio_counts.most_common():
    print(f"{label}: {count}")

O: 102832
I-SKILL: 7078
I-DEGREE: 687
I-COLLEGE: 682
I-DESIGNATION: 537
B-DESIGNATION: 425
B-COMPANY: 281
B-COLLEGE: 275
B-SKILL: 236
B-NAME: 223
I-COMPANY: 223
B-DEGREE: 188
B-EMAIL: 94
I-EMAIL: 47
B-EXPERIENCE: 27
B-LOCATION: 25
I-EXPERIENCE: 19
B-GRADUATION_YEAR: 18
I-NAME: 14
I-LOCATION: 9
I-GRADUATION_YEAR: 5

In [ ]:
from sklearn.model_selection import train_test_split

train_data, temp_data = train_test_split(
    bio_data,
    test_size=0.2,
    random_state=42
)

val_data, test_data = train_test_split(
    temp_data,
    test_size=0.5,
    random_state=42
)

print("Training:", len(train_data))
print("Validation:", len(val_data))
print("Test:", len(test_data))

Training: 176
Validation: 22
Test: 22

In [ ]:
from datasets import Dataset, DatasetDict

train_dataset = Dataset.from_list(train_data)
val_dataset = Dataset.from_list(val_data)
test_dataset = Dataset.from_list(test_data)

ner_dataset = DatasetDict({
    "train": train_dataset,
    "validation": val_dataset,
    "test": test_dataset
})

print(ner_dataset)

DatasetDict({
    train: Dataset({
        features: ['tokens', 'ner_tags'],
        num_rows: 176
    })
    validation: Dataset({
        features: ['tokens', 'ner_tags'],
        num_rows: 22
    })
    test: Dataset({
        features: ['tokens', 'ner_tags'],
        num_rows: 22
    })
})

In [ ]:
def tokenize_and_align_labels(examples):
    tokenized = tokenizer(
        examples["tokens"],
        truncation=True,
        is_split_into_words=True
    )

    all_labels = []

    for i, labels in enumerate(examples["ner_tags"]):
        word_ids = tokenized.word_ids(batch_index=i)
        previous_word_id = None
        label_ids = []

        for word_id in word_ids:
            if word_id is None:
                label_ids.append(-100)
            elif word_id != previous_word_id:
                label_ids.append(labels[word_id])
            else:
                label_ids.append(-100)

            previous_word_id = word_id

        all_labels.append(label_ids)

    tokenized["labels"] = all_labels
    return tokenized


tokenized_ner_dataset = ner_dataset.map(
    tokenize_and_align_labels,
    batched=True
)

print(tokenized_ner_dataset)

Map:   0%|          | 0/176 [00:00<?, ? examples/s]

Map:   0%|          | 0/22 [00:00<?, ? examples/s]

Map:   0%|          | 0/22 [00:00<?, ? examples/s]

DatasetDict({
    train: Dataset({
        features: ['tokens', 'ner_tags', 'input_ids', 'token_type_ids', 'attention_mask', 'labels'],
        num_rows: 176
    })
    validation: Dataset({
        features: ['tokens', 'ner_tags', 'input_ids', 'token_type_ids', 'attention_mask', 'labels'],
        num_rows: 22
    })
    test: Dataset({
        features: ['tokens', 'ner_tags', 'input_ids', 'token_type_ids', 'attention_mask', 'labels'],
        num_rows: 22
    })
})

In [ ]:
from transformers import AutoModelForTokenClassification

model = AutoModelForTokenClassification.from_pretrained(
    model_name,
    num_labels=len(NER_LABELS),
    id2label=id2label,
    label2id=label2id
)

print("Model ready for training!")
print("Number of labels:", len(NER_LABELS))

Loading weights:   0%|          | 0/100 [00:00<?, ?it/s]

[transformers] DistilBertForTokenClassification LOAD REPORT from: distilbert-base-cased
Key                     | Status     |
------------------------+------------+-
vocab_layer_norm.bias   | UNEXPECTED |
vocab_transform.bias    | UNEXPECTED |
vocab_layer_norm.weight | UNEXPECTED |
vocab_projector.bias    | UNEXPECTED |
vocab_transform.weight  | UNEXPECTED |
classifier.weight       | MISSING    |
classifier.bias         | MISSING    |

Notes:
- UNEXPECTED:	can be ignored when loading from different task/architecture; not ok if you expect identical arch.
- MISSING:	those params were newly initialized because missing from the checkpoint. Consider training on your downstream task.

Model ready for training!
Number of labels: 23

In [ ]:
from transformers import TrainingArguments, Trainer

training_args = TrainingArguments(
    output_dir="./resume_ner_model",
    eval_strategy="epoch",
    save_strategy="epoch",
    learning_rate=2e-5,
    per_device_train_batch_size=4,
    per_device_eval_batch_size=4,
    num_train_epochs=5,
    weight_decay=0.01,
    logging_steps=20,
    report_to="none"
)

trainer = Trainer(
    model=model,
    args=training_args,
    train_dataset=tokenized_ner_dataset["train"],
    eval_dataset=tokenized_ner_dataset["validation"],
    processing_class=tokenizer,
    data_collator=data_collator
)

print("Trainer ready!")

Trainer ready!

In [ ]:
trainer.train()

NameError: name 'trainer' is not defined

In [ ]:
trainer.train()

NameError: name 'trainer' is not defined

In [ ]:
from transformers import TrainingArguments, Trainer

training_args = TrainingArguments(
    output_dir="./resume_ner_model",
    eval_strategy="epoch",
    save_strategy="epoch",
    learning_rate=2e-5,
    per_device_train_batch_size=4,
    per_device_eval_batch_size=4,
    num_train_epochs=5,
    weight_decay=0.01,
    logging_steps=20,
    report_to="none"
)

trainer = Trainer(
    model=model,
    args=training_args,
    train_dataset=tokenized_ner_dataset["train"],
    eval_dataset=tokenized_ner_dataset["validation"],
    processing_class=tokenizer,
    data_collator=data_collator
)

print("Trainer ready!")

NameError: name 'model' is not defined

In [ ]:
from transformers import AutoModelForTokenClassification

model_name = "distilbert-base-cased"

model = AutoModelForTokenClassification.from_pretrained(
    model_name,
    num_labels=len(NER_LABELS),
    id2label=id2label,
    label2id=label2id
)

print("Model ready!")
print("Labels:", len(NER_LABELS))

NameError: name 'NER_LABELS' is not defined

In [ ]:
NER_LABELS = [
    "O",
    "B-NAME", "I-NAME",
    "B-EMAIL", "I-EMAIL",
    "B-PHONE", "I-PHONE",
    "B-LOCATION", "I-LOCATION",
    "B-COMPANY", "I-COMPANY",
    "B-DESIGNATION", "I-DESIGNATION",
    "B-COLLEGE", "I-COLLEGE",
    "B-DEGREE", "I-DEGREE",
    "B-GRADUATION_YEAR", "I-GRADUATION_YEAR",
    "B-SKILL", "I-SKILL",
    "B-EXPERIENCE", "I-EXPERIENCE"
]

label2id = {label: i for i, label in enumerate(NER_LABELS)}
id2label = {i: label for i, label in enumerate(NER_LABELS)}

print("Labels restored:", len(NER_LABELS))

Labels restored: 23

In [ ]:
import json
from sklearn.model_selection import train_test_split
from datasets import Dataset, DatasetDict
from transformers import (
    AutoTokenizer,
    AutoModelForTokenClassification,
    DataCollatorForTokenClassification,
    TrainingArguments,
    Trainer
)

# 1. Load real DataTurks data
data = []

with open("Entity Recognition in Resumes.json", "r", encoding="utf-8") as f:
    for line in f:
        line = line.strip()
        if line:
            data.append(json.loads(line))

# 2. Map dataset labels to our labels
label_map = {
    "Name": "NAME",
    "Email Address": "EMAIL",
    "Location": "LOCATION",
    "Companies worked at": "COMPANY",
    "Designation": "DESIGNATION",
    "College Name": "COLLEGE",
    "Degree": "DEGREE",
    "Graduation Year": "GRADUATION_YEAR",
    "Skills": "SKILL",
    "Years of Experience": "EXPERIENCE"
}

# 3. Convert character annotations → word BIO labels
def convert_to_bio(resume):
    text = resume["content"]
    annotations = []

    for ann in resume["annotation"]:
        if not ann.get("label"):
            continue

        original_label = ann["label"][0]

        if original_label not in label_map:
            continue

        label = label_map[original_label]

        for point in ann.get("points", []):
            annotations.append(
                (point["start"], point["end"], label)
            )

    annotations.sort(key=lambda x: x[0])

    words = []
    current_word = ""
    word_start = None

    for i, char in enumerate(text):
        if char.isspace():
            if current_word:
                words.append((current_word, word_start, i))
                current_word = ""
                word_start = None
        else:
            if current_word == "":
                word_start = i
            current_word += char

    if current_word:
        words.append((current_word, word_start, len(text)))

    bio_labels = []

    for word, start, end in words:
        label = "O"

        for ent_start, ent_end, ent_label in annotations:
            if start >= ent_start and end <= ent_end:
                label = (
                    "B-" + ent_label
                    if start == ent_start
                    else "I-" + ent_label
                )
                break

        bio_labels.append(label)

    return {
        "tokens": [w[0] for w in words],
        "ner_tags": [label2id[x] for x in bio_labels]
    }

bio_data = [convert_to_bio(x) for x in data]

# 4. Split data
train_data, temp_data = train_test_split(
    bio_data, test_size=0.2, random_state=42
)

val_data, test_data = train_test_split(
    temp_data, test_size=0.5, random_state=42
)

ner_dataset = DatasetDict({
    "train": Dataset.from_list(train_data),
    "validation": Dataset.from_list(val_data),
    "test": Dataset.from_list(test_data)
})

# 5. Tokenizer
model_name = "distilbert-base-cased"
tokenizer = AutoTokenizer.from_pretrained(model_name)

def tokenize_and_align_labels(examples):
    tokenized = tokenizer(
        examples["tokens"],
        truncation=True,
        is_split_into_words=True
    )

    all_labels = []

    for i, labels in enumerate(examples["ner_tags"]):
        word_ids = tokenized.word_ids(batch_index=i)
        previous_word_id = None
        label_ids = []

        for word_id in word_ids:
            if word_id is None:
                label_ids.append(-100)
            elif word_id != previous_word_id:
                label_ids.append(labels[word_id])
            else:
                label_ids.append(-100)

            previous_word_id = word_id

        all_labels.append(label_ids)

    tokenized["labels"] = all_labels
    return tokenized

tokenized_ner_dataset = ner_dataset.map(
    tokenize_and_align_labels,
    batched=True
)

# 6. Model
model = AutoModelForTokenClassification.from_pretrained(
    model_name,
    num_labels=len(NER_LABELS),
    id2label=id2label,
    label2id=label2id
)

# 7. Data collator
data_collator = DataCollatorForTokenClassification(
    tokenizer=tokenizer
)

# 8. Trainer
training_args = TrainingArguments(
    output_dir="./resume_ner_model",
    eval_strategy="epoch",
    save_strategy="epoch",
    learning_rate=2e-5,
    per_device_train_batch_size=4,
    per_device_eval_batch_size=4,
    num_train_epochs=5,
    weight_decay=0.01,
    logging_steps=20,
    report_to="none"
)

trainer = Trainer(
    model=model,
    args=training_args,
    train_dataset=tokenized_ner_dataset["train"],
    eval_dataset=tokenized_ner_dataset["validation"],
    processing_class=tokenizer,
    data_collator=data_collator
)

print("================================")
print("SETUP COMPLETE")
print("Resumes:", len(data))
print("Training:", len(train_data))
print("Validation:", len(val_data))
print("Test:", len(test_data))
print("BIO labels:", len(NER_LABELS))
print("================================")

FileNotFoundError: [Errno 2] No such file or directory: 'Entity Recognition in Resumes.json'

In [ ]:
!wget -q "https://www.kaggle.com/api/v1/datasets/download/dataturks/resume-entities-for-ner" -O dataturks.zip
!unzip -o dataturks.zip
!ls -lh "Entity Recognition in Resumes.json"

Archive:  dataturks.zip
  inflating: Entity Recognition in Resumes.json
-rw-r--r-- 1 root root 1.2M Oct  2  2019 'Entity Recognition in Resumes.json'

In [ ]:
trainer.train()

NameError: name 'trainer' is not defined

In [ ]:
import json
from sklearn.model_selection import train_test_split
from datasets import Dataset, DatasetDict
from transformers import (
    AutoTokenizer,
    AutoModelForTokenClassification,
    DataCollatorForTokenClassification,
    TrainingArguments,
    Trainer
)

# ---------- LABELS ----------
NER_LABELS = [
    "O",
    "B-NAME", "I-NAME",
    "B-EMAIL", "I-EMAIL",
    "B-PHONE", "I-PHONE",
    "B-LOCATION", "I-LOCATION",
    "B-COMPANY", "I-COMPANY",
    "B-DESIGNATION", "I-DESIGNATION",
    "B-COLLEGE", "I-COLLEGE",
    "B-DEGREE", "I-DEGREE",
    "B-GRADUATION_YEAR", "I-GRADUATION_YEAR",
    "B-SKILL", "I-SKILL",
    "B-EXPERIENCE", "I-EXPERIENCE"
]

label2id = {label: i for i, label in enumerate(NER_LABELS)}
id2label = {i: label for i, label in enumerate(NER_LABELS)}

# ---------- LOAD DATA ----------
data = []

with open("Entity Recognition in Resumes.json", "r", encoding="utf-8") as f:
    for line in f:
        line = line.strip()
        if line:
            data.append(json.loads(line))

print("Loaded resumes:", len(data))

# ---------- LABEL MAPPING ----------
label_map = {
    "Name": "NAME",
    "Email Address": "EMAIL",
    "Location": "LOCATION",
    "Companies worked at": "COMPANY",
    "Designation": "DESIGNATION",
    "College Name": "COLLEGE",
    "Degree": "DEGREE",
    "Graduation Year": "GRADUATION_YEAR",
    "Skills": "SKILL",
    "Years of Experience": "EXPERIENCE"
}

# ---------- CHARACTER → BIO ----------
def convert_to_bio(resume):
    text = resume["content"]
    annotations = []

    for ann in resume["annotation"]:
        if not ann.get("label"):
            continue

        original_label = ann["label"][0]

        if original_label not in label_map:
            continue

        for point in ann.get("points", []):
            annotations.append((
                point["start"],
                point["end"],
                label_map[original_label]
            ))

    annotations.sort(key=lambda x: x[0])

    words = []
    current_word = ""
    word_start = None

    for i, char in enumerate(text):
        if char.isspace():
            if current_word:
                words.append((current_word, word_start, i))
                current_word = ""
                word_start = None
        else:
            if not current_word:
                word_start = i
            current_word += char

    if current_word:
        words.append((current_word, word_start, len(text)))

    bio_labels = []

    for word, start, end in words:
        tag = "O"

        for ent_start, ent_end, ent_label in annotations:
            if start >= ent_start and end <= ent_end:
                tag = (
                    "B-" + ent_label
                    if start == ent_start
                    else "I-" + ent_label
                )
                break

        bio_labels.append(tag)

    return {
        "tokens": [w[0] for w in words],
        "ner_tags": [label2id[x] for x in bio_labels]
    }

bio_data = [convert_to_bio(x) for x in data]

# ---------- SPLIT ----------
train_data, temp_data = train_test_split(
    bio_data,
    test_size=0.20,
    random_state=42
)

val_data, test_data = train_test_split(
    temp_data,
    test_size=0.50,
    random_state=42
)

ner_dataset = DatasetDict({
    "train": Dataset.from_list(train_data),
    "validation": Dataset.from_list(val_data),
    "test": Dataset.from_list(test_data)
})

print("Train:", len(train_data))
print("Validation:", len(val_data))
print("Test:", len(test_data))

# ---------- TOKENIZER ----------
model_name = "distilbert-base-cased"
tokenizer = AutoTokenizer.from_pretrained(model_name)

def tokenize_and_align_labels(examples):
    tokenized = tokenizer(
        examples["tokens"],
        truncation=True,
        is_split_into_words=True
    )

    all_labels = []

    for i, labels in enumerate(examples["ner_tags"]):
        word_ids = tokenized.word_ids(batch_index=i)
        previous_word_id = None
        label_ids = []

        for word_id in word_ids:
            if word_id is None:
                label_ids.append(-100)
            elif word_id != previous_word_id:
                label_ids.append(labels[word_id])
            else:
                label_ids.append(-100)

            previous_word_id = word_id

        all_labels.append(label_ids)

    tokenized["labels"] = all_labels
    return tokenized

tokenized_ner_dataset = ner_dataset.map(
    tokenize_and_align_labels,
    batched=True
)

# ---------- MODEL ----------
model = AutoModelForTokenClassification.from_pretrained(
    model_name,
    num_labels=len(NER_LABELS),
    id2label=id2label,
    label2id=label2id
)

# ---------- COLLATOR ----------
data_collator = DataCollatorForTokenClassification(
    tokenizer=tokenizer
)

# ---------- TRAINER ----------
training_args = TrainingArguments(
    output_dir="./resume_ner_model",
    eval_strategy="epoch",
    save_strategy="epoch",
    learning_rate=2e-5,
    per_device_train_batch_size=4,
    per_device_eval_batch_size=4,
    num_train_epochs=5,
    weight_decay=0.01,
    logging_steps=20,
    report_to="none"
)

trainer = Trainer(
    model=model,
    args=training_args,
    train_dataset=tokenized_ner_dataset["train"],
    eval_dataset=tokenized_ner_dataset["validation"],
    processing_class=tokenizer,
    data_collator=data_collator
)

print("\n==============================")
print("SETUP COMPLETE")
print("Resumes:", len(data))
print("BIO labels:", len(NER_LABELS))
print("Trainer ready!")
print("==============================")

Loaded resumes: 220
Train: 176
Validation: 22
Test: 22

config.json:   0%|          | 0.00/465 [00:00<?, ?B/s]

tokenizer_config.json:   0%|          | 0.00/49.0 [00:00<?, ?B/s]

vocab.txt:   0%|          | 0.00/213k [00:00<?, ?B/s]

Warning: You are sending unauthenticated requests to the HF Hub. Please set a HF_TOKEN to enable higher rate limits and faster downloads.
WARNING:huggingface_hub.utils._http:Warning: You are sending unauthenticated requests to the HF Hub. Please set a HF_TOKEN to enable higher rate limits and faster downloads.

tokenizer.json:   0%|          | 0.00/436k [00:00<?, ?B/s]

Map:   0%|          | 0/176 [00:00<?, ? examples/s]

Map:   0%|          | 0/22 [00:00<?, ? examples/s]

Map:   0%|          | 0/22 [00:00<?, ? examples/s]

model.safetensors: reconstructing file:   0%|          |  0.00B /  263MB

model.safetensors: downloading bytes:           |  0.00B

Loading weights:   0%|          | 0/100 [00:00<?, ?it/s]

[transformers] DistilBertForTokenClassification LOAD REPORT from: distilbert-base-cased
Key                     | Status     |
------------------------+------------+-
vocab_transform.weight  | UNEXPECTED |
vocab_layer_norm.weight | UNEXPECTED |
vocab_layer_norm.bias   | UNEXPECTED |
vocab_projector.bias    | UNEXPECTED |
vocab_transform.bias    | UNEXPECTED |
classifier.weight       | MISSING    |
classifier.bias         | MISSING    |

Notes:
- UNEXPECTED:	can be ignored when loading from different task/architecture; not ok if you expect identical arch.
- MISSING:	those params were newly initialized because missing from the checkpoint. Consider training on your downstream task.

==============================
SETUP COMPLETE
Resumes: 220
BIO labels: 23
Trainer ready!
==============================

In [ ]:
trainer.train()

/usr/local/lib/python3.13/dist-packages/torch/utils/data/dataloader.py:775: UserWarning: 'pin_memory' argument is set as true but no accelerator is found, then device pinned memory won't be used.
  super().__init__(loader)

Writing model shards:   0%|          | 0/1 [00:00<?, ?it/s]

/usr/local/lib/python3.13/dist-packages/torch/utils/data/dataloader.py:775: UserWarning: 'pin_memory' argument is set as true but no accelerator is found, then device pinned memory won't be used.
  super().__init__(loader)

Writing model shards:   0%|          | 0/1 [00:00<?, ?it/s]

/usr/local/lib/python3.13/dist-packages/torch/utils/data/dataloader.py:775: UserWarning: 'pin_memory' argument is set as true but no accelerator is found, then device pinned memory won't be used.
  super().__init__(loader)

Writing model shards:   0%|          | 0/1 [00:00<?, ?it/s]

/usr/local/lib/python3.13/dist-packages/torch/utils/data/dataloader.py:775: UserWarning: 'pin_memory' argument is set as true but no accelerator is found, then device pinned memory won't be used.
  super().__init__(loader)

Writing model shards:   0%|          | 0/1 [00:00<?, ?it/s]

/usr/local/lib/python3.13/dist-packages/torch/utils/data/dataloader.py:775: UserWarning: 'pin_memory' argument is set as true but no accelerator is found, then device pinned memory won't be used.
  super().__init__(loader)

Writing model shards:   0%|          | 0/1 [00:00<?, ?it/s]

TrainOutput(global_step=220, training_loss=0.41618881008841774, metrics={'train_runtime': 2977.9104, 'train_samples_per_second': 0.296, 'train_steps_per_second': 0.074, 'total_flos': 114611980850640.0, 'train_loss': 0.41618881008841774, 'epoch': 5.0})

In [ ]:
metrics = trainer.evaluate(
    tokenized_ner_dataset["test"]
)

print(metrics)

/usr/local/lib/python3.13/dist-packages/torch/utils/data/dataloader.py:775: UserWarning: 'pin_memory' argument is set as true but no accelerator is found, then device pinned memory won't be used.
  super().__init__(loader)

{'eval_loss': 0.22104722261428833}

In [ ]:
from transformers import pipeline

ner_pipeline = pipeline(
    "token-classification",
    model=model,
    tokenizer=tokenizer,
    aggregation_strategy="simple"
)

test_text = """
My name is Rahul Kumar.
I completed B.Tech in Computer Science from ABC University.
My email is rahul.kumar@gmail.com.
My phone number is 9876543210.
I worked at Microsoft as a Software Engineer.
My skills include Python, Java and SQL.
I live in Hyderabad.
"""

results = ner_pipeline(test_text)

for r in results:
    print(f"{r['word']} -> {r['entity_group']} ({r['score']:.2f})")

My -> NAME (0.25)

In [ ]:
for r in results:
    print(f"{r['word']:<30} -> {r['entity_group']:<20} confidence={r['score']:.3f}")

My                             -> NAME                 confidence=0.245

In [ ]:
test_text = "Rahul Kumar works at Microsoft."

results = ner_pipeline(test_text)

for r in results:
    print(f"{r['word']} -> {r['entity_group']} ({r['score']:.3f})")

Ra -> NAME (0.211)

In [ ]:
# Check one annotated entity against the generated BIO labels

resume = data[0]
bio_example = bio_data[0]

for token, tag_id in zip(
    bio_example["tokens"],
    bio_example["ner_tags"]
):
    if tag_id != label2id["O"]:
        print(token, "->", id2label[tag_id])

Abhishek -> B-NAME
Application -> B-DESIGNATION
Development -> I-DESIGNATION
Indeed: -> B-EMAIL
indeed.com/r/Abhishek-Jha/10e7a8cb732bc43a -> I-EMAIL
Application -> B-DESIGNATION
Development -> I-DESIGNATION
B.E -> B-DESIGNATION
in -> I-DESIGNATION
Information -> I-DESIGNATION
science -> I-DESIGNATION
and -> I-DESIGNATION
engineering -> I-DESIGNATION
B.v.b -> B-COLLEGE
college -> I-COLLEGE
of -> I-COLLEGE
engineering -> I-COLLEGE
and -> I-COLLEGE
2017 -> B-GRADUATION_YEAR
Woodbine -> B-COLLEGE
modern -> I-COLLEGE
Kendriya -> B-COLLEGE
C -> B-SKILL
(Less -> I-SKILL
than -> I-SKILL
1 -> I-SKILL
year), -> I-SKILL
Database -> I-SKILL
(Less -> I-SKILL
than -> I-SKILL
1 -> I-SKILL
year), -> I-SKILL
Database -> I-SKILL
Management -> I-SKILL
(Less -> I-SKILL
than -> I-SKILL
1 -> I-SKILL
year), -> I-SKILL
Database -> I-SKILL
Management -> I-SKILL
System -> I-SKILL
(Less -> I-SKILL
than -> I-SKILL
1 -> I-SKILL
year), -> I-SKILL
Java -> I-SKILL
(Less -> I-SKILL
than -> I-SKILL
1 -> I-SKILL
• -> I-SKILL
Programming -> I-SKILL
language: -> I-SKILL
C, -> I-SKILL
C++, -> I-SKILL
Java -> I-SKILL
• -> I-SKILL
Oracle -> I-SKILL
PeopleSoft -> I-SKILL
• -> I-SKILL
Internet -> I-SKILL
Of -> I-SKILL
Things -> I-SKILL
• -> I-SKILL
Machine -> I-SKILL
Learning -> I-SKILL
• -> I-SKILL
Database -> I-SKILL
Management -> I-SKILL
System -> I-SKILL
• -> I-SKILL
Computer -> I-SKILL
Networks -> I-SKILL
• -> I-SKILL
Operating -> I-SKILL
System -> I-SKILL
worked -> I-SKILL
on: -> I-SKILL
Linux, -> I-SKILL
Windows, -> I-SKILL
Mac -> I-SKILL
Non -> I-SKILL
- -> I-SKILL
Technical -> I-SKILL
Skills -> I-SKILL
• -> I-SKILL
Honest -> I-SKILL
and -> I-SKILL
Hard-Working -> I-SKILL
• -> I-SKILL
Tolerant -> I-SKILL
and -> I-SKILL
Flexible -> I-SKILL
to -> I-SKILL
Different -> I-SKILL
Situations -> I-SKILL
• -> I-SKILL
Polite -> I-SKILL
and -> I-SKILL
Calm -> I-SKILL
• -> I-SKILL

In [ ]:
# ============================================================
# FINAL CLEAN NER DATA PREPARATION
# ============================================================

import json
import re
from collections import Counter
from sklearn.model_selection import train_test_split
from datasets import Dataset, DatasetDict

# ------------------------------------------------------------
# 1. LABELS
# ------------------------------------------------------------

ENTITY_TYPES = [
    "NAME",
    "LOCATION",
    "COMPANY",
    "DESIGNATION",
    "COLLEGE",
    "DEGREE",
    "GRADUATION_YEAR",
    "SKILL",
    "EXPERIENCE"
]

NER_LABELS = ["O"]

for entity in ENTITY_TYPES:
    NER_LABELS.append("B-" + entity)
    NER_LABELS.append("I-" + entity)

label2id = {label: i for i, label in enumerate(NER_LABELS)}
id2label = {i: label for i, label in enumerate(NER_LABELS)}

print("BIO labels:", len(NER_LABELS))
print(NER_LABELS)


# ------------------------------------------------------------
# 2. LOAD REAL DATATURKS DATA
# ------------------------------------------------------------

data = []

with open(
    "Entity Recognition in Resumes.json",
    "r",
    encoding="utf-8"
) as f:

    for line in f:
        line = line.strip()

        if line:
            data.append(json.loads(line))

print("Resumes loaded:", len(data))


# ------------------------------------------------------------
# 3. DATASET LABEL MAPPING
# ------------------------------------------------------------

source_to_target = {
    "Name": "NAME",
    "Location": "LOCATION",
    "Companies worked at": "COMPANY",
    "Designation": "DESIGNATION",
    "College Name": "COLLEGE",
    "Degree": "DEGREE",
    "Graduation Year": "GRADUATION_YEAR",
    "Skills": "SKILL",
    "Years of Experience": "EXPERIENCE"
}


# ------------------------------------------------------------
# 4. CLEAN CHARACTER SPANS
# ------------------------------------------------------------

def get_clean_annotations(resume):

    text = resume["content"]
    annotations = []

    for ann in resume.get("annotation", []):

        labels = ann.get("label", [])

        if not labels:
            continue

        source_label = labels[0]

        if source_label not in source_to_target:
            continue

        target_label = source_to_target[source_label]

        for point in ann.get("points", []):

            start = point.get("start")
            end = point.get("end")

            if start is None or end is None:
                continue

            # Safety
            start = max(0, int(start))
            end = min(len(text), int(end))

            if start >= end:
                continue

            entity_text = text[start:end]

            # Ignore empty/whitespace annotations
            if not entity_text.strip():
                continue

            annotations.append(
                (start, end, target_label)
            )

    # Remove exact duplicates
    annotations = list(set(annotations))

    # Sort by start position and then longest span first
    annotations.sort(
        key=lambda x: (x[0], -(x[1] - x[0]))
    )

    # --------------------------------------------------------
    # Remove conflicting overlapping annotations.
    # Keep the longest annotation when spans overlap.
    # --------------------------------------------------------

    cleaned = []

    for candidate in annotations:

        start, end, label = candidate

        overlaps = False

        for existing_start, existing_end, existing_label in cleaned:

            if (
                start < existing_end
                and end > existing_start
            ):
                overlaps = True
                break

        if not overlaps:
            cleaned.append(candidate)

    cleaned.sort(key=lambda x: x[0])

    return cleaned


# ------------------------------------------------------------
# 5. CHARACTER SPANS → WORD-LEVEL BIO
# ------------------------------------------------------------

def resume_to_bio(resume):

    text = resume["content"]

    annotations = get_clean_annotations(resume)

    # --------------------------------------------------------
    # Proper whitespace word spans
    # --------------------------------------------------------

    words = []

    for match in re.finditer(r"\S+", text):

        words.append(
            (
                match.group(),
                match.start(),
                match.end()
            )
        )

    tokens = []
    tags = []

    for word, word_start, word_end in words:

        selected_label = None
        is_beginning = False

        # Find entity containing this word
        for ent_start, ent_end, ent_label in annotations:

            # Word overlaps entity
            if (
                word_start < ent_end
                and word_end > ent_start
            ):

                selected_label = ent_label

                # Word starts at entity beginning
                if word_start <= ent_start:
                    is_beginning = True

                break

        tokens.append(word)

        if selected_label is None:

            tags.append("O")

        else:

            if is_beginning:
                tags.append("B-" + selected_label)
            else:
                tags.append("I-" + selected_label)

    return {
        "tokens": tokens,
        "ner_tags": [
            label2id[tag]
            for tag in tags
        ]
    }


# ------------------------------------------------------------
# 6. CONVERT ALL RESUMES
# ------------------------------------------------------------

bio_data = []

for resume in data:

    converted = resume_to_bio(resume)

    if len(converted["tokens"]) > 0:
        bio_data.append(converted)

print("BIO resumes:", len(bio_data))


# ------------------------------------------------------------
# 7. CHECK LABEL DISTRIBUTION
# ------------------------------------------------------------

counts = Counter()

for example in bio_data:

    for tag_id in example["ner_tags"]:

        counts[id2label[tag_id]] += 1

print("\nLABEL DISTRIBUTION")
print("=" * 40)

for label, count in counts.most_common():

    print(f"{label:25s} {count}")


# ------------------------------------------------------------
# 8. SPLIT
# ------------------------------------------------------------

train_data, temp_data = train_test_split(
    bio_data,
    test_size=0.20,
    random_state=42
)

val_data, test_data = train_test_split(
    temp_data,
    test_size=0.50,
    random_state=42
)

print("\nDATA SPLIT")
print("=" * 40)
print("Training   :", len(train_data))
print("Validation :", len(val_data))
print("Test       :", len(test_data))


# ------------------------------------------------------------
# 9. HUGGING FACE DATASETS
# ------------------------------------------------------------

ner_dataset = DatasetDict({

    "train": Dataset.from_list(train_data),

    "validation": Dataset.from_list(val_data),

    "test": Dataset.from_list(test_data)
})


# ------------------------------------------------------------
# 10. SANITY CHECK
# ------------------------------------------------------------

print("\nSANITY CHECK")
print("=" * 40)

example = train_data[0]

for token, tag_id in zip(
    example["tokens"],
    example["ner_tags"]
):

    tag = id2label[tag_id]

    if tag != "O":

        print(
            f"{token:30s} -> {tag}"
        )

print("\nFINAL DATA PREPARATION COMPLETE")

BIO labels: 19
['O', 'B-NAME', 'I-NAME', 'B-LOCATION', 'I-LOCATION', 'B-COMPANY', 'I-COMPANY', 'B-DESIGNATION', 'I-DESIGNATION', 'B-COLLEGE', 'I-COLLEGE', 'B-DEGREE', 'I-DEGREE', 'B-GRADUATION_YEAR', 'I-GRADUATION_YEAR', 'B-SKILL', 'I-SKILL', 'B-EXPERIENCE', 'I-EXPERIENCE']
Resumes loaded: 220
BIO resumes: 220

LABEL DISTRIBUTION
========================================
O                         100225
I-SKILL                   7300
I-COLLEGE                 892
I-DESIGNATION             885
I-DEGREE                  830
B-COMPANY                 623
B-DESIGNATION             491
I-COMPANY                 462
B-SKILL                   419
B-LOCATION                414
B-COLLEGE                 302
B-DEGREE                  284
B-GRADUATION_YEAR         226
B-NAME                    224
I-NAME                    217
I-EXPERIENCE              50
B-EXPERIENCE              31
I-LOCATION                28
I-GRADUATION_YEAR         22

DATA SPLIT
========================================
Training   : 176
Validation : 22
Test       : 22

SANITY CHECK
========================================
Sharan                         -> B-NAME
Adla                           -> I-NAME
4yrs.                          -> B-EXPERIENCE
Specialist                     -> B-DESIGNATION
II,                            -> I-DESIGNATION
Marketing                      -> I-DESIGNATION
Bachelors                      -> B-DEGREE
in                             -> I-DEGREE
Computer                       -> I-DEGREE
Science                        -> I-DEGREE
M.                             -> B-COLLEGE
V.                             -> I-COLLEGE
G.                             -> I-COLLEGE
R                              -> I-COLLEGE
College                        -> I-COLLEGE
of                             -> I-COLLEGE
Engineering                    -> I-COLLEGE
MPC                            -> B-DEGREE
subject                        -> I-DEGREE
Gowtham                        -> B-COLLEGE
Jr.                            -> I-COLLEGE
College                        -> I-COLLEGE
SSC                            -> B-DEGREE
Vignan                         -> B-COLLEGE
Vidyalayam                     -> I-COLLEGE
High                           -> I-COLLEGE
School                         -> I-COLLEGE

FINAL DATA PREPARATION COMPLETE

In [ ]:
from transformers import (
    AutoTokenizer,
    AutoModelForTokenClassification,
    DataCollatorForTokenClassification,
    TrainingArguments,
    Trainer
)

# Tokenizer
model_name = "distilbert-base-cased"

tokenizer = AutoTokenizer.from_pretrained(model_name)


# Tokenization + BIO alignment
def tokenize_and_align_labels(examples):

    tokenized = tokenizer(
        examples["tokens"],
        truncation=True,
        is_split_into_words=True
    )

    all_labels = []

    for i, labels in enumerate(examples["ner_tags"]):

        word_ids = tokenized.word_ids(batch_index=i)

        previous_word_id = None
        label_ids = []

        for word_id in word_ids:

            if word_id is None:
                label_ids.append(-100)

            elif word_id != previous_word_id:
                label_ids.append(labels[word_id])

            else:
                label_ids.append(-100)

            previous_word_id = word_id

        all_labels.append(label_ids)

    tokenized["labels"] = all_labels

    return tokenized


tokenized_ner_dataset = ner_dataset.map(
    tokenize_and_align_labels,
    batched=True
)


# Model
model = AutoModelForTokenClassification.from_pretrained(
    model_name,
    num_labels=len(NER_LABELS),
    id2label=id2label,
    label2id=label2id
)


# Data collator
data_collator = DataCollatorForTokenClassification(
    tokenizer=tokenizer
)


# Training configuration
training_args = TrainingArguments(
    output_dir="./resume_ner_final",
    eval_strategy="epoch",
    save_strategy="epoch",

    learning_rate=2e-5,

    per_device_train_batch_size=4,
    per_device_eval_batch_size=4,

    num_train_epochs=5,

    weight_decay=0.01,

    logging_steps=20,

    report_to="none"
)


# Trainer
trainer = Trainer(
    model=model,
    args=training_args,

    train_dataset=tokenized_ner_dataset["train"],
    eval_dataset=tokenized_ner_dataset["validation"],

    processing_class=tokenizer,
    data_collator=data_collator
)

print("================================")
print("FINAL TRAINER READY")
print("Labels:", len(NER_LABELS))
print("Training resumes:", len(train_data))
print("Validation resumes:", len(val_data))
print("Test resumes:", len(test_data))
print("================================")

Map:   0%|          | 0/176 [00:00<?, ? examples/s]

Map:   0%|          | 0/22 [00:00<?, ? examples/s]

Map:   0%|          | 0/22 [00:00<?, ? examples/s]

Loading weights:   0%|          | 0/100 [00:00<?, ?it/s]

[transformers] DistilBertForTokenClassification LOAD REPORT from: distilbert-base-cased
Key                     | Status     |
------------------------+------------+-
vocab_transform.weight  | UNEXPECTED |
vocab_layer_norm.weight | UNEXPECTED |
vocab_layer_norm.bias   | UNEXPECTED |
vocab_projector.bias    | UNEXPECTED |
vocab_transform.bias    | UNEXPECTED |
classifier.weight       | MISSING    |
classifier.bias         | MISSING    |

Notes:
- UNEXPECTED:	can be ignored when loading from different task/architecture; not ok if you expect identical arch.
- MISSING:	those params were newly initialized because missing from the checkpoint. Consider training on your downstream task.

================================
FINAL TRAINER READY
Labels: 19
Training resumes: 176
Validation resumes: 22
Test resumes: 22
================================

In [ ]:
# FINAL PRE-TRAINING CHECK

print("================================")
print("FINAL PRE-TRAINING VALIDATION")
print("================================")

# Check dataset sizes
print("Train:", len(tokenized_ner_dataset["train"]))
print("Validation:", len(tokenized_ner_dataset["validation"]))
print("Test:", len(tokenized_ner_dataset["test"]))

# Check label count
print("Number of labels:", len(NER_LABELS))

# Check model output size
print("Model classifier output:", model.classifier.out_proj.out_features if hasattr(model.classifier, "out_proj") else model.classifier.out_features)

# Check one tokenized example
sample = tokenized_ner_dataset["train"][0]

print("\nToken/label alignment sample:")
tokens = tokenizer.convert_ids_to_tokens(sample["input_ids"])

shown = 0
for token, label_id in zip(tokens, sample["labels"]):
    if label_id != -100:
        print(f"{token:20} -> {NER_LABELS[label_id]}")
        shown += 1
    if shown >= 30:
        break

# Check for invalid labels
invalid = []

for split in ["train", "validation", "test"]:
    for example in tokenized_ner_dataset[split]:
        for x in example["labels"]:
            if x != -100 and (x < 0 or x >= len(NER_LABELS)):
                invalid.append(x)

print("\nInvalid label IDs:", len(invalid))

print("\n================================")
if len(invalid) == 0:
    print("PRE-TRAINING CHECK PASSED")
    print("================================")
    print("Training can proceed.")
else:
    print("CHECK FAILED — DO NOT TRAIN")
    print("================================")

================================
FINAL PRE-TRAINING VALIDATION
================================
Train: 176
Validation: 22
Test: 22
Number of labels: 19
Model classifier output: 19

Token/label alignment sample:
S                    -> B-NAME
Ad                   -> I-NAME
-                    -> O
Em                   -> O
me                   -> O
on                   -> O
Indeed               -> O
indeed               -> O
•                    -> O
Having               -> O
4                    -> B-EXPERIENCE
of                   -> O
solid                -> O
work                 -> O
experience           -> O
in                   -> O
designing            -> O
experiences          -> O
for                  -> O
Digital              -> O
(                    -> O
Mobile               -> O
and                  -> O
Print                -> O
media                -> O
•                    -> O
Hands                -> O
experience           -> O
with                 -> O
tools                -> O

Invalid label IDs: 0

================================
PRE-TRAINING CHECK PASSED
================================
Training can proceed.

In [1]:
trainer.train()

NameError: name 'trainer' is not defined

In [2]:
from transformers import (
    AutoTokenizer,
    AutoModelForTokenClassification,
    DataCollatorForTokenClassification,
    TrainingArguments,
    Trainer
)

model_name = "distilbert-base-cased"
tokenizer = AutoTokenizer.from_pretrained(model_name)

def tokenize_and_align_labels(examples):
    tokenized = tokenizer(
        examples["tokens"],
        truncation=True,
        is_split_into_words=True
    )

    all_labels = []

    for i, labels in enumerate(examples["ner_tags"]):
        word_ids = tokenized.word_ids(batch_index=i)
        previous_word_id = None
        label_ids = []

        for word_id in word_ids:
            if word_id is None:
                label_ids.append(-100)
            elif word_id != previous_word_id:
                label_ids.append(labels[word_id])
            else:
                label_ids.append(-100)

            previous_word_id = word_id

        all_labels.append(label_ids)

    tokenized["labels"] = all_labels
    return tokenized

tokenized_ner_dataset = ner_dataset.map(
    tokenize_and_align_labels,
    batched=True
)

model = AutoModelForTokenClassification.from_pretrained(
    model_name,
    num_labels=len(NER_LABELS),
    id2label=id2label,
    label2id=label2id
)

data_collator = DataCollatorForTokenClassification(
    tokenizer=tokenizer
)

training_args = TrainingArguments(
    output_dir="./resume_ner_final",
    eval_strategy="epoch",
    save_strategy="epoch",
    learning_rate=2e-5,
    per_device_train_batch_size=4,
    per_device_eval_batch_size=4,
    num_train_epochs=5,
    weight_decay=0.01,
    logging_steps=20,
    report_to="none"
)

trainer = Trainer(
    model=model,
    args=training_args,
    train_dataset=tokenized_ner_dataset["train"],
    eval_dataset=tokenized_ner_dataset["validation"],
    processing_class=tokenizer,
    data_collator=data_collator
)

print("FINAL TRAINER READY")

Warning: You are sending unauthenticated requests to the HF Hub. Please set a HF_TOKEN to enable higher rate limits and faster downloads.
WARNING:huggingface_hub.utils._http:Warning: You are sending unauthenticated requests to the HF Hub. Please set a HF_TOKEN to enable higher rate limits and faster downloads.

config.json:   0%|          | 0.00/465 [00:00<?, ?B/s]

tokenizer_config.json:   0%|          | 0.00/49.0 [00:00<?, ?B/s]

vocab.txt:   0%|          | 0.00/213k [00:00<?, ?B/s]

tokenizer.json:   0%|          | 0.00/436k [00:00<?, ?B/s]

NameError: name 'ner_dataset' is not defined

In [3]:
Resumes loaded: 220
BIO resumes: 220

Training   : 176
Validation : 22
Test       : 22

SyntaxError: invalid syntax (3463190071.py, line 1)

In [5]:
import json
from datasets import Dataset, DatasetDict
from sklearn.model_selection import train_test_split
print("================================")

================================

In [7]:
import json
from datasets import Dataset, DatasetDict
from sklearn.model_selection import train_test_split

In [8]:
import json
from datasets import Dataset, DatasetDict
from sklearn.model_selection import train_test_split
import re

# 1. LABELS
ENTITY_TYPES = [
    "NAME",
    "LOCATION",
    "COMPANY",
    "DESIGNATION",
    "COLLEGE",
    "DEGREE",
    "GRADUATION_YEAR",
    "SKILL",
    "EXPERIENCE"
]

NER_LABELS = ["O"]

for entity in ENTITY_TYPES:
    NER_LABELS.append(f"B-{entity}")
    NER_LABELS.append(f"I-{entity}")

label2id = {label: i for i, label in enumerate(NER_LABELS)}
id2label = {i: label for label, i in label2id.items()}

print("BIO labels:", len(NER_LABELS))


# 2. LOAD DATA
data = []

with open("Entity Recognition in Resumes.json", "r", encoding="utf-8") as f:
    for line in f:
        line = line.strip()
        if line:
            data.append(json.loads(line))

print("Resumes loaded:", len(data))


# 3. SOURCE LABEL → TARGET LABEL
source_to_target = {
    "Name": "NAME",
    "Location": "LOCATION",
    "Companies worked at": "COMPANY",
    "Designation": "DESIGNATION",
    "College Name": "COLLEGE",
    "Degree": "DEGREE",
    "Graduation Year": "GRADUATION_YEAR",
    "Skills": "SKILL",
    "Years of Experience": "EXPERIENCE"
}


# 4. CONVERT EACH RESUME
def convert_resume(item):

    text = item["content"]
    annotations = item.get("annotation", [])

    spans = []

    for ann in annotations:

        labels = ann.get("label", [])

        if not labels:
            continue

        source_label = labels[0]

        if source_label not in source_to_target:
            continue

        points = ann.get("points", [])

        if not points:
            continue

        point = points[0]

        start = point.get("start")
        end = point.get("end")

        if start is None or end is None:
            continue

        start = max(0, int(start))
        end = min(len(text) - 1, int(end))

        if start > end:
            continue

        entity = source_to_target[source_label]

        while start <= end and text[start].isspace():
            start += 1

        while end >= start and text[end].isspace():
            end -= 1

        if start > end:
            continue

        spans.append((start, end, entity))

    # Remove duplicates
    spans = list(set(spans))

    # Sort
    spans.sort(key=lambda x: (x[0], -(x[1] - x[0])))

    # Remove overlapping annotations
    clean_spans = []

    for span in spans:

        start, end, entity = span

        overlap = False

        for old_start, old_end, old_entity in clean_spans:
            if not (end < old_start or start > old_end):
                overlap = True
                break

        if not overlap:
            clean_spans.append(span)

    # Tokenize into whitespace tokens
    tokens = []
    token_spans = []

    for match in re.finditer(r"\S+", text):
        tokens.append(match.group())
        token_spans.append(
            (match.start(), match.end() - 1)
        )

    ner_tags = ["O"] * len(tokens)

    # Apply BIO labels
    for start, end, entity in clean_spans:

        matched_tokens = []

        for i, (tok_start, tok_end) in enumerate(token_spans):

            if tok_end < start:
                continue

            if tok_start > end:
                break

            matched_tokens.append(i)

        if not matched_tokens:
            continue

        for j, token_idx in enumerate(matched_tokens):

            if j == 0:
                ner_tags[token_idx] = f"B-{entity}"
            else:
                ner_tags[token_idx] = f"I-{entity}"

    return {
        "tokens": tokens,
        "ner_tags": [label2id[x] for x in ner_tags]
    }


# 5. CONVERT ALL RESUMES
converted = []

for item in data:

    result = convert_resume(item)

    if len(result["tokens"]) > 0:
        converted.append(result)

print("BIO resumes:", len(converted))


# 6. SPLIT DATA
train_data, temp_data = train_test_split(
    converted,
    test_size=0.20,
    random_state=42
)

val_data, test_data = train_test_split(
    temp_data,
    test_size=0.50,
    random_state=42
)


# 7. CREATE HF DATASET
ner_dataset = DatasetDict({
    "train": Dataset.from_list(train_data),
    "validation": Dataset.from_list(val_data),
    "test": Dataset.from_list(test_data)
})


print()
print("================================")
print("DATASET READY")
print("================================")
print("Training   :", len(train_data))
print("Validation :", len(val_data))
print("Test       :", len(test_data))
print("================================")

BIO labels: 19

FileNotFoundError: [Errno 2] No such file or directory: 'Entity Recognition in Resumes.json'

In [9]:
!wget -q "https://www.kaggle.com/api/v1/datasets/download/dataturks/resume-entities-for-ner" -O dataturks.zip
!unzip -o dataturks.zip

Archive:  dataturks.zip
  inflating: Entity Recognition in Resumes.json

In [10]:
import os

print(os.listdir())

['.config', 'dataturks.zip', 'Entity Recognition in Resumes.json', 'sample_data']

In [11]:
import json
from datasets import Dataset, DatasetDict
from sklearn.model_selection import train_test_split
import re

# 1. LABELS
ENTITY_TYPES = [
    "NAME",
    "LOCATION",
    "COMPANY",
    "DESIGNATION",
    "COLLEGE",
    "DEGREE",
    "GRADUATION_YEAR",
    "SKILL",
    "EXPERIENCE"
]

NER_LABELS = ["O"]

for entity in ENTITY_TYPES:
    NER_LABELS.append(f"B-{entity}")
    NER_LABELS.append(f"I-{entity}")

label2id = {label: i for i, label in enumerate(NER_LABELS)}
id2label = {i: label for label, i in label2id.items()}

print("BIO labels:", len(NER_LABELS))


# 2. LOAD DATA
data = []

with open("Entity Recognition in Resumes.json", "r", encoding="utf-8") as f:
    for line in f:
        line = line.strip()
        if line:
            data.append(json.loads(line))

print("Resumes loaded:", len(data))


# 3. SOURCE LABEL → TARGET LABEL
source_to_target = {
    "Name": "NAME",
    "Location": "LOCATION",
    "Companies worked at": "COMPANY",
    "Designation": "DESIGNATION",
    "College Name": "COLLEGE",
    "Degree": "DEGREE",
    "Graduation Year": "GRADUATION_YEAR",
    "Skills": "SKILL",
    "Years of Experience": "EXPERIENCE"
}


# 4. CONVERT EACH RESUME
def convert_resume(item):

    text = item["content"]
    annotations = item.get("annotation", [])

    spans = []

    for ann in annotations:

        labels = ann.get("label", [])

        if not labels:
            continue

        source_label = labels[0]

        if source_label not in source_to_target:
            continue

        points = ann.get("points", [])

        if not points:
            continue

        point = points[0]

        start = point.get("start")
        end = point.get("end")

        if start is None or end is None:
            continue

        start = max(0, int(start))
        end = min(len(text) - 1, int(end))

        if start > end:
            continue

        entity = source_to_target[source_label]

        while start <= end and text[start].isspace():
            start += 1

        while end >= start and text[end].isspace():
            end -= 1

        if start > end:
            continue

        spans.append((start, end, entity))

    # Remove duplicates
    spans = list(set(spans))

    # Sort
    spans.sort(key=lambda x: (x[0], -(x[1] - x[0])))

    # Remove overlapping annotations
    clean_spans = []

    for span in spans:

        start, end, entity = span

        overlap = False

        for old_start, old_end, old_entity in clean_spans:
            if not (end < old_start or start > old_end):
                overlap = True
                break

        if not overlap:
            clean_spans.append(span)

    # Tokenize into whitespace tokens
    tokens = []
    token_spans = []

    for match in re.finditer(r"\S+", text):
        tokens.append(match.group())
        token_spans.append(
            (match.start(), match.end() - 1)
        )

    ner_tags = ["O"] * len(tokens)

    # Apply BIO labels
    for start, end, entity in clean_spans:

        matched_tokens = []

        for i, (tok_start, tok_end) in enumerate(token_spans):

            if tok_end < start:
                continue

            if tok_start > end:
                break

            matched_tokens.append(i)

        if not matched_tokens:
            continue

        for j, token_idx in enumerate(matched_tokens):

            if j == 0:
                ner_tags[token_idx] = f"B-{entity}"
            else:
                ner_tags[token_idx] = f"I-{entity}"

    return {
        "tokens": tokens,
        "ner_tags": [label2id[x] for x in ner_tags]
    }


# 5. CONVERT ALL RESUMES
converted = []

for item in data:

    result = convert_resume(item)

    if len(result["tokens"]) > 0:
        converted.append(result)

print("BIO resumes:", len(converted))


# 6. SPLIT DATA
train_data, temp_data = train_test_split(
    converted,
    test_size=0.20,
    random_state=42
)

val_data, test_data = train_test_split(
    temp_data,
    test_size=0.50,
    random_state=42
)


# 7. CREATE HF DATASET
ner_dataset = DatasetDict({
    "train": Dataset.from_list(train_data),
    "validation": Dataset.from_list(val_data),
    "test": Dataset.from_list(test_data)
})


print()
print("================================")
print("DATASET READY")
print("================================")
print("Training   :", len(train_data))
print("Validation :", len(val_data))
print("Test       :", len(test_data))
print("================================")

BIO labels: 19
Resumes loaded: 220
BIO resumes: 220

================================
DATASET READY
================================
Training   : 176
Validation : 22
Test       : 22
================================

In [12]:
from transformers import (
    AutoTokenizer,
    AutoModelForTokenClassification,
    DataCollatorForTokenClassification,
    TrainingArguments,
    Trainer
)

model_name = "distilbert-base-cased"

tokenizer = AutoTokenizer.from_pretrained(model_name)


def tokenize_and_align_labels(examples):

    tokenized = tokenizer(
        examples["tokens"],
        truncation=True,
        is_split_into_words=True
    )

    all_labels = []

    for i, labels in enumerate(examples["ner_tags"]):

        word_ids = tokenized.word_ids(batch_index=i)

        previous_word_id = None
        label_ids = []

        for word_id in word_ids:

            if word_id is None:
                label_ids.append(-100)

            elif word_id != previous_word_id:
                label_ids.append(labels[word_id])

            else:
                label_ids.append(-100)

            previous_word_id = word_id

        all_labels.append(label_ids)

    tokenized["labels"] = all_labels

    return tokenized


# Tokenize dataset
tokenized_ner_dataset = ner_dataset.map(
    tokenize_and_align_labels,
    batched=True
)


# Create model
model = AutoModelForTokenClassification.from_pretrained(
    model_name,
    num_labels=len(NER_LABELS),
    id2label=id2label,
    label2id=label2id
)


# Data collator
data_collator = DataCollatorForTokenClassification(
    tokenizer=tokenizer
)


# Training configuration
training_args = TrainingArguments(
    output_dir="./resume_ner_final",

    eval_strategy="epoch",
    save_strategy="epoch",

    learning_rate=2e-5,

    per_device_train_batch_size=4,
    per_device_eval_batch_size=4,

    num_train_epochs=5,

    weight_decay=0.01,

    logging_steps=20,

    report_to="none"
)


# Trainer
trainer = Trainer(
    model=model,
    args=training_args,

    train_dataset=tokenized_ner_dataset["train"],
    eval_dataset=tokenized_ner_dataset["validation"],

    processing_class=tokenizer,

    data_collator=data_collator
)


print("================================")
print("FINAL TRAINER READY")
print("================================")
print("Labels:", len(NER_LABELS))
print("Training resumes:", len(train_data))
print("Validation resumes:", len(val_data))
print("Test resumes:", len(test_data))
print("================================")

Map:   0%|          | 0/176 [00:00<?, ? examples/s]

Map:   0%|          | 0/22 [00:00<?, ? examples/s]

Map:   0%|          | 0/22 [00:00<?, ? examples/s]

model.safetensors: reconstructing file:   0%|          |  0.00B /  263MB

model.safetensors: downloading bytes:           |  0.00B

Loading weights:   0%|          | 0/100 [00:00<?, ?it/s]

[transformers] DistilBertForTokenClassification LOAD REPORT from: distilbert-base-cased
Key                     | Status     |
------------------------+------------+-
vocab_projector.bias    | UNEXPECTED |
vocab_layer_norm.weight | UNEXPECTED |
vocab_layer_norm.bias   | UNEXPECTED |
vocab_transform.weight  | UNEXPECTED |
vocab_transform.bias    | UNEXPECTED |
classifier.weight       | MISSING    |
classifier.bias         | MISSING    |

Notes:
- UNEXPECTED:	can be ignored when loading from different task/architecture; not ok if you expect identical arch.
- MISSING:	those params were newly initialized because missing from the checkpoint. Consider training on your downstream task.

================================
FINAL TRAINER READY
================================
Labels: 19
Training resumes: 176
Validation resumes: 22
Test resumes: 22
================================

In [13]:
trainer.train()

/usr/local/lib/python3.13/dist-packages/torch/utils/data/dataloader.py:775: UserWarning: 'pin_memory' argument is set as true but no accelerator is found, then device pinned memory won't be used.
  super().__init__(loader)

Writing model shards:   0%|          | 0/1 [00:00<?, ?it/s]

/usr/local/lib/python3.13/dist-packages/torch/utils/data/dataloader.py:775: UserWarning: 'pin_memory' argument is set as true but no accelerator is found, then device pinned memory won't be used.
  super().__init__(loader)

Writing model shards:   0%|          | 0/1 [00:00<?, ?it/s]

/usr/local/lib/python3.13/dist-packages/torch/utils/data/dataloader.py:775: UserWarning: 'pin_memory' argument is set as true but no accelerator is found, then device pinned memory won't be used.
  super().__init__(loader)

Writing model shards:   0%|          | 0/1 [00:00<?, ?it/s]

/usr/local/lib/python3.13/dist-packages/torch/utils/data/dataloader.py:775: UserWarning: 'pin_memory' argument is set as true but no accelerator is found, then device pinned memory won't be used.
  super().__init__(loader)

Writing model shards:   0%|          | 0/1 [00:00<?, ?it/s]

/usr/local/lib/python3.13/dist-packages/torch/utils/data/dataloader.py:775: UserWarning: 'pin_memory' argument is set as true but no accelerator is found, then device pinned memory won't be used.
  super().__init__(loader)

Writing model shards:   0%|          | 0/1 [00:00<?, ?it/s]

TrainOutput(global_step=220, training_loss=0.49431709592992606, metrics={'train_runtime': 3505.5424, 'train_samples_per_second': 0.251, 'train_steps_per_second': 0.063, 'total_flos': 114603694697232.0, 'train_loss': 0.49431709592992606, 'epoch': 5.0})

In [14]:
!pip install -q seqeval

     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 43.6/43.6 kB 600.0 kB/s eta 0:00:00
  error: subprocess-exited-with-error

  × python setup.py egg_info did not run successfully.
  │ exit code: 1
  ╰─> See above for output.

  note: This error originates from a subprocess, and is likely not a problem with pip.
  Preparing metadata (setup.py) ... error
error: metadata-generation-failed

× Encountered error while generating package metadata.
╰─> See above for output.

note: This is an issue with the package mentioned above, not pip.
hint: See above for details.

In [15]:
import numpy as np
from collections import defaultdict

# Get predictions on unseen test set
pred_output = trainer.predict(tokenized_ner_dataset["test"])

predictions = np.argmax(pred_output.predictions, axis=2)
true_labels = pred_output.label_ids

# Collect entity-level token statistics
stats = defaultdict(lambda: {"tp": 0, "fp": 0, "fn": 0})

for pred_seq, true_seq in zip(predictions, true_labels):

    for pred_id, true_id in zip(pred_seq, true_seq):

        # Ignore special/padding tokens
        if true_id == -100:
            continue

        pred_label = id2label[pred_id]
        true_label = id2label[true_id]

        # Ignore O for per-entity statistics
        if true_label != "O":

            if pred_label == true_label:
                stats[true_label]["tp"] += 1
            else:
                stats[true_label]["fn"] += 1
                if pred_label != "O":
                    stats[pred_label]["fp"] += 1

        elif pred_label != "O":
            stats[pred_label]["fp"] += 1


print("==============================================")
print("NER TEST SET EVALUATION")
print("==============================================")

total_tp = total_fp = total_fn = 0

for label in NER_LABELS:

    if label == "O":
        continue

    tp = stats[label]["tp"]
    fp = stats[label]["fp"]
    fn = stats[label]["fn"]

    precision = tp / (tp + fp) if (tp + fp) else 0
    recall = tp / (tp + fn) if (tp + fn) else 0
    f1 = (
        2 * precision * recall / (precision + recall)
        if (precision + recall)
        else 0
    )

    total_tp += tp
    total_fp += fp
    total_fn += fn

    print(
        f"{label:20} "
        f"Precision: {precision:.3f}  "
        f"Recall: {recall:.3f}  "
        f"F1: {f1:.3f}  "
        f"(TP={tp}, FP={fp}, FN={fn})"
    )

# Overall micro scores
precision = total_tp / (total_tp + total_fp) if (total_tp + total_fp) else 0
recall = total_tp / (total_tp + total_fn) if (total_tp + total_fn) else 0
f1 = (
    2 * precision * recall / (precision + recall)
    if (precision + recall)
    else 0
)

print("\n==============================================")
print("OVERALL TOKEN-LEVEL RESULTS")
print("==============================================")
print(f"Precision : {precision:.3f}")
print(f"Recall    : {recall:.3f}")
print(f"F1        : {f1:.3f}")
print("==============================================")

/usr/local/lib/python3.13/dist-packages/torch/utils/data/dataloader.py:775: UserWarning: 'pin_memory' argument is set as true but no accelerator is found, then device pinned memory won't be used.
  super().__init__(loader)

==============================================
NER TEST SET EVALUATION
==============================================
B-NAME               Precision: 1.000  Recall: 0.957  F1: 0.978  (TP=22, FP=0, FN=1)
I-NAME               Precision: 0.880  Recall: 0.957  F1: 0.917  (TP=22, FP=3, FN=1)
B-LOCATION           Precision: 0.609  Recall: 0.538  F1: 0.571  (TP=14, FP=9, FN=12)
I-LOCATION           Precision: 0.000  Recall: 0.000  F1: 0.000  (TP=0, FP=0, FN=2)
B-COMPANY            Precision: 0.900  Recall: 0.209  F1: 0.340  (TP=9, FP=1, FN=34)
I-COMPANY            Precision: 0.000  Recall: 0.000  F1: 0.000  (TP=0, FP=0, FN=28)
B-DESIGNATION        Precision: 0.857  Recall: 0.120  F1: 0.211  (TP=6, FP=1, FN=44)
I-DESIGNATION        Precision: 0.430  Recall: 0.544  F1: 0.480  (TP=43, FP=57, FN=36)
B-COLLEGE            Precision: 0.000  Recall: 0.000  F1: 0.000  (TP=0, FP=0, FN=13)
I-COLLEGE            Precision: 0.400  Recall: 0.261  F1: 0.316  (TP=12, FP=18, FN=34)
B-DEGREE             Precision: 0.000  Recall: 0.000  F1: 0.000  (TP=0, FP=0, FN=14)
I-DEGREE             Precision: 0.000  Recall: 0.000  F1: 0.000  (TP=0, FP=1, FN=29)
B-GRADUATION_YEAR    Precision: 0.000  Recall: 0.000  F1: 0.000  (TP=0, FP=0, FN=15)
I-GRADUATION_YEAR    Precision: 0.000  Recall: 0.000  F1: 0.000  (TP=0, FP=0, FN=0)
B-SKILL              Precision: 0.000  Recall: 0.000  F1: 0.000  (TP=0, FP=0, FN=19)
I-SKILL              Precision: 0.276  Recall: 0.661  F1: 0.389  (TP=37, FP=97, FN=19)
B-EXPERIENCE         Precision: 0.000  Recall: 0.000  F1: 0.000  (TP=0, FP=0, FN=2)
I-EXPERIENCE         Precision: 0.000  Recall: 0.000  F1: 0.000  (TP=0, FP=0, FN=2)

==============================================
OVERALL TOKEN-LEVEL RESULTS
==============================================
Precision : 0.469
Recall    : 0.351
F1        : 0.401
==============================================